# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..errors.bad_request_error import BadRequestError
from ..errors.internal_server_error import InternalServerError
from ..errors.service_unavailable_error import ServiceUnavailableError
from ..errors.unauthorized_error import UnauthorizedError
from ..types.deposit_funds_response import DepositFundsResponse
from ..types.entrypointfield import Entrypointfield
from ..types.payabli_error_body import PayabliErrorBody
from ..types.paypoint_id import PaypointId
from pydantic import ValidationError

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class RawFundingClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def deposit_funds(
        self,
        *,
        amount: float,
        entrypoint: Entrypointfield,
        account_id: str,
        paypoint_id: typing.Optional[PaypointId] = OMIT,
        same_day_ach: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> HttpResponse[DepositFundsResponse]:
        """
        Deposits funds into a paypoint's available payout balance. Deposited funds enter a pending state and aren't available for instant payouts until confirmed through FBO reconciliation.

        Parameters
        ----------
        amount : float
            The amount to deposit, in dollars. Must be greater than zero.

        entrypoint : Entrypointfield
            The entry point identifier for the paypoint receiving the deposit.

        account_id : str
            The remittance account ID to withdraw funds from.

        paypoint_id : typing.Optional[PaypointId]
            The paypoint ID. Optional if the entry point uniquely identifies the paypoint.

        same_day_ach : typing.Optional[bool]
            When `true` and the request is submitted before 2 PM ET, the deposit processes as same-day ACH. If the request is submitted after 2 PM ET, it processes as standard ACH regardless of this flag.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[DepositFundsResponse]
            Success
        """
        _endpoint_auth_headers = self._client_wrapper.get_auth_headers_for_endpoint(
            security=[{"BearerAuth": []}, {"APIKeyAuth": []}]
        )
        _response = self._client_wrapper.httpx_client.request(
            "Funding/depositFunds",
            method="POST",
            json={
                "amount": amount,
                "entrypoint": entrypoint,
                "accountId": account_id,
                "paypointId": paypoint_id,
                "sameDayAch": same_day_ach,
            },
            headers={
                **_endpoint_auth_headers,
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DepositFundsResponse,
                    parse_obj_as(
                        type_=DepositFundsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        PayabliErrorBody,
                        parse_obj_as(
                            type_=PayabliErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 503:
                raise ServiceUnavailableError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        PayabliErrorBody,
                        parse_obj_as(
                            type_=PayabliErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawFundingClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def deposit_funds(
        self,
        *,
        amount: float,
        entrypoint: Entrypointfield,
        account_id: str,
        paypoint_id: typing.Optional[PaypointId] = OMIT,
        same_day_ach: typing.Optional[bool] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> AsyncHttpResponse[DepositFundsResponse]:
        """
        Deposits funds into a paypoint's available payout balance. Deposited funds enter a pending state and aren't available for instant payouts until confirmed through FBO reconciliation.

        Parameters
        ----------
        amount : float
            The amount to deposit, in dollars. Must be greater than zero.

        entrypoint : Entrypointfield
            The entry point identifier for the paypoint receiving the deposit.

        account_id : str
            The remittance account ID to withdraw funds from.

        paypoint_id : typing.Optional[PaypointId]
            The paypoint ID. Optional if the entry point uniquely identifies the paypoint.

        same_day_ach : typing.Optional[bool]
            When `true` and the request is submitted before 2 PM ET, the deposit processes as same-day ACH. If the request is submitted after 2 PM ET, it processes as standard ACH regardless of this flag.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[DepositFundsResponse]
            Success
        """
        _endpoint_auth_headers = await self._client_wrapper.async_get_auth_headers_for_endpoint(
            security=[{"BearerAuth": []}, {"APIKeyAuth": []}]
        )
        _response = await self._client_wrapper.httpx_client.request(
            "Funding/depositFunds",
            method="POST",
            json={
                "amount": amount,
                "entrypoint": entrypoint,
                "accountId": account_id,
                "paypointId": paypoint_id,
                "sameDayAch": same_day_ach,
            },
            headers={
                **_endpoint_auth_headers,
                "content-type": "application/json",
            },
            request_options=request_options,
            omit=OMIT,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DepositFundsResponse,
                    parse_obj_as(
                        type_=DepositFundsResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 400:
                raise BadRequestError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        PayabliErrorBody,
                        parse_obj_as(
                            type_=PayabliErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 503:
                raise ServiceUnavailableError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        PayabliErrorBody,
                        parse_obj_as(
                            type_=PayabliErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
