# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .customer_id import CustomerId
from .is_success import IsSuccess
from .response_text import ResponseText


class AddPayoutSubscriptionResponse(UniversalBaseModel):
    """
    Success response
    """

    is_success: typing_extensions.Annotated[
        typing.Optional[IsSuccess], FieldMetadata(alias="isSuccess"), pydantic.Field(alias="isSuccess")
    ] = None
    response_text: typing_extensions.Annotated[
        ResponseText, FieldMetadata(alias="responseText"), pydantic.Field(alias="responseText")
    ]
    response_data: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="responseData"),
        pydantic.Field(alias="responseData", description="The identifier of the newly created payout subscription."),
    ]
    """
    The identifier of the newly created payout subscription.
    """

    customer_id: typing_extensions.Annotated[
        typing.Optional[CustomerId],
        FieldMetadata(alias="customerId"),
        pydantic.Field(
            alias="customerId", description="The identifier of the vendor associated with the payout subscription."
        ),
    ] = None
    """
    The identifier of the vendor associated with the payout subscription.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
