# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .authcode import Authcode
from .avs_response_text import AvsResponseText
from .cvv_response_text import CvvResponseText
from .method_reference_id import MethodReferenceId
from .referenceidtrans import Referenceidtrans
from .result_code import ResultCode
from .resulttext import Resulttext
from .vendoridtrans import Vendoridtrans


class AuthCapturePayoutResponseData(UniversalBaseModel):
    auth_code: typing_extensions.Annotated[
        typing.Optional[Authcode], FieldMetadata(alias="authCode"), pydantic.Field(alias="authCode")
    ] = None
    reference_id: typing_extensions.Annotated[
        Referenceidtrans, FieldMetadata(alias="referenceId"), pydantic.Field(alias="referenceId")
    ]
    result_code: typing_extensions.Annotated[
        ResultCode, FieldMetadata(alias="resultCode"), pydantic.Field(alias="resultCode")
    ]
    result_text: typing_extensions.Annotated[
        Resulttext, FieldMetadata(alias="resultText"), pydantic.Field(alias="resultText")
    ]
    avs_response_text: typing_extensions.Annotated[
        typing.Optional[AvsResponseText],
        FieldMetadata(alias="avsResponseText"),
        pydantic.Field(alias="avsResponseText"),
    ] = None
    cvv_response_text: typing_extensions.Annotated[
        typing.Optional[CvvResponseText],
        FieldMetadata(alias="cvvResponseText"),
        pydantic.Field(alias="cvvResponseText"),
    ] = None
    customer_id: typing_extensions.Annotated[
        Vendoridtrans,
        FieldMetadata(alias="customerId"),
        pydantic.Field(
            alias="customerId",
            description="Payabli-generated unique ID of the vendor on the payout. Returns the same value as `vendorId`, or `0` when no vendor is associated.",
        ),
    ]
    """
    Payabli-generated unique ID of the vendor on the payout. Returns the same value as `vendorId`, or `0` when no vendor is associated.
    """

    vendor_id: typing_extensions.Annotated[
        Vendoridtrans,
        FieldMetadata(alias="vendorId"),
        pydantic.Field(
            alias="vendorId",
            description="Payabli-generated unique ID of the vendor on the payout. Returns the same value as `customerId`, or `0` when no vendor is associated.",
        ),
    ]
    """
    Payabli-generated unique ID of the vendor on the payout. Returns the same value as `customerId`, or `0` when no vendor is associated.
    """

    method_reference_id: typing_extensions.Annotated[
        typing.Optional[MethodReferenceId],
        FieldMetadata(alias="methodReferenceId"),
        pydantic.Field(alias="methodReferenceId"),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
