# This file was auto-generated by Fern from our API Definition.

import typing

BankReviewDecisionReason = typing.Union[
    typing.Literal["CreditDecline", "FraudDecline", "KybKycDecline", "Withdrawn"], typing.Any
]
