# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .verification_code import VerificationCode


class BankVerificationMetadata(UniversalBaseModel):
    """
    The outcome of automatic bank account verification.
    """

    verification_result: typing_extensions.Annotated[
        VerificationCode, FieldMetadata(alias="verificationResult"), pydantic.Field(alias="verificationResult")
    ]
    account_response_code: typing_extensions.Annotated[
        typing.Optional[VerificationCode],
        FieldMetadata(alias="accountResponseCode"),
        pydantic.Field(
            alias="accountResponseCode", description="The account-level verification code. Null when not returned."
        ),
    ] = None
    """
    The account-level verification code. Null when not returned.
    """

    customer_response_code: typing_extensions.Annotated[
        typing.Optional[VerificationCode],
        FieldMetadata(alias="customerResponseCode"),
        pydantic.Field(
            alias="customerResponseCode", description="The customer-level verification code. Null when not returned."
        ),
    ] = None
    """
    The customer-level verification code. Null when not returned.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
