# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .bank_account_change_parameters_type import BankAccountChangeParametersType
from .bank_account_services import BankAccountServices
from .case_management_bank_account_function import CaseManagementBankAccountFunction


class BankAccountChangeParameters(UniversalBaseModel):
    """
    The bank-account-change details stored on a case. The raw account and
    routing numbers are write-only and never appear here — only a vault token
    (`bankToken`) and non-sensitive details.
    """

    type: BankAccountChangeParametersType = pydantic.Field()
    """
    The parameters type discriminator.
    """

    nickname: str = pydantic.Field()
    """
    A label for the account.
    """

    bank_name: typing_extensions.Annotated[
        str, FieldMetadata(alias="bankName"), pydantic.Field(alias="bankName", description="The name of the bank.")
    ]
    """
    The name of the bank.
    """

    bank_token: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="bankToken"),
        pydantic.Field(
            alias="bankToken",
            description="A vault token referencing the tokenized bank account. The raw account and routing numbers are never returned.",
        ),
    ]
    """
    A vault token referencing the tokenized bank account. The raw account and routing numbers are never returned.
    """

    account_type: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="accountType"),
        pydantic.Field(alias="accountType", description="The account type, such as `Checking` or `Savings`."),
    ]
    """
    The account type, such as `Checking` or `Savings`.
    """

    bank_account_holder_name: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="bankAccountHolderName"),
        pydantic.Field(
            alias="bankAccountHolderName",
            description="The account holder's name, taken from the paypoint's legal name.",
        ),
    ]
    """
    The account holder's name, taken from the paypoint's legal name.
    """

    bank_account_holder_type: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="bankAccountHolderType"),
        pydantic.Field(
            alias="bankAccountHolderType", description="The account holder type, such as `personal` or `business`."
        ),
    ]
    """
    The account holder type, such as `personal` or `business`.
    """

    bank_account_function: typing_extensions.Annotated[
        CaseManagementBankAccountFunction,
        FieldMetadata(alias="bankAccountFunction"),
        pydantic.Field(alias="bankAccountFunction"),
    ]
    services: BankAccountServices
    default: bool = pydantic.Field()
    """
    Whether this is the default account for the selected services.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
