# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .billable_event import BillableEvent
from .billing_entity import BillingEntity
from .fee_type_value import FeeTypeValue


class BillingProfileResponse(UniversalBaseModel):
    """
    A billing profile assigned to an entity, returned by the View profile
    endpoint. A profile is a named configuration of billable events, each with
    one or more fee schedules. Profiles are append-only versioned — every edit
    mints a new version.
    """

    id: int = pydantic.Field()
    """
    Unique, server-generated profile identifier.
    """

    version_id: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="versionId"),
        pydantic.Field(alias="versionId", description="Identifier of this specific version of the profile."),
    ]
    """
    Identifier of this specific version of the profile.
    """

    version_number: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="versionNumber"),
        pydantic.Field(
            alias="versionNumber",
            description="Sequential version counter. Starts at `1` and increments on every edit\n(profiles are append-only versioned, not mutated in place).",
        ),
    ]
    """
    Sequential version counter. Starts at `1` and increments on every edit
    (profiles are append-only versioned, not mutated in place).
    """

    business: BillingEntity
    name: str = pydantic.Field()
    """
    Descriptive name for the profile.
    """

    fee_type: typing_extensions.Annotated[FeeTypeValue, FieldMetadata(alias="feeType"), pydantic.Field(alias="feeType")]
    created_at: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="createdAt"),
        pydantic.Field(alias="createdAt", description="When this version was created."),
    ]
    """
    When this version was created.
    """

    updated_at: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="updatedAt"),
        pydantic.Field(alias="updatedAt", description="When this version was last updated."),
    ]
    """
    When this version was last updated.
    """

    parent_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="parentId"),
        pydantic.Field(
            alias="parentId",
            description="Parent-entity reference used for inheritance and permission checks,\nformatted as `{entityType}:{entityId}` (for example, `1:2` is\norganization `2`). Org-level profiles reference their own organization;\npaypoint-level profiles reference their parent organization.",
        ),
    ]
    """
    Parent-entity reference used for inheritance and permission checks,
    formatted as `{entityType}:{entityId}` (for example, `1:2` is
    organization `2`). Org-level profiles reference their own organization;
    paypoint-level profiles reference their parent organization.
    """

    billable_events: typing_extensions.Annotated[
        typing.List[BillableEvent],
        FieldMetadata(alias="billableEvents"),
        pydantic.Field(alias="billableEvents", description="The chargeable events this profile covers."),
    ]
    """
    The chargeable events this profile covers.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
