# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .billing_profile_record import BillingProfileRecord
from .billing_profile_summary import BillingProfileSummary


class BillingProfileQueryResponse(UniversalBaseModel):
    """
    A page of billing profiles that belong to an organization, returned by the
    List profiles endpoint. This is the data behind the Profile Library table in
    the Payabli Portal.
    """

    summary: BillingProfileSummary
    records: typing.List[BillingProfileRecord] = pydantic.Field()
    """
    The billing profiles on this page. Empty when the org has no profiles.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
