# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .event_group_value import EventGroupValue
from .event_source_value import EventSourceValue
from .event_type_value import EventTypeValue
from .fee_schedule import FeeSchedule
from .region_type_value import RegionTypeValue
from .service_group_value import ServiceGroupValue
from .service_type_value import ServiceTypeValue
from .service_value import ServiceValue


class BillableEvent(UniversalBaseModel):
    """
    A chargeable action covered by a billing profile, with the fee schedule(s)
    that apply to it.
    """

    id: int = pydantic.Field()
    """
    Event identifier.
    """

    name: str = pydantic.Field()
    """
    Internal label for the event, for example `payin-card-auth-all`.
    """

    vertical: ServiceGroupValue
    service: ServiceValue
    service_type: typing_extensions.Annotated[
        ServiceTypeValue, FieldMetadata(alias="serviceType"), pydantic.Field(alias="serviceType")
    ]
    event_type: typing_extensions.Annotated[
        EventTypeValue, FieldMetadata(alias="eventType"), pydantic.Field(alias="eventType")
    ]
    event_group: typing_extensions.Annotated[
        EventGroupValue, FieldMetadata(alias="eventGroup"), pydantic.Field(alias="eventGroup")
    ]
    event_source: typing_extensions.Annotated[
        EventSourceValue, FieldMetadata(alias="eventSource"), pydantic.Field(alias="eventSource")
    ]
    region_type: typing_extensions.Annotated[
        RegionTypeValue, FieldMetadata(alias="regionType"), pydantic.Field(alias="regionType")
    ]
    fee_schedules: typing_extensions.Annotated[
        typing.List[FeeSchedule],
        FieldMetadata(alias="feeSchedules"),
        pydantic.Field(alias="feeSchedules", description="The fee schedule(s) that apply to this event."),
    ]
    """
    The fee schedule(s) that apply to this event.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
