# This file was auto-generated by Fern from our API Definition.

import typing

CaseState = typing.Union[
    typing.Literal[
        "Submitted",
        "Verifying",
        "PendingReview",
        "Assigned",
        "PendingResponse",
        "Escalated",
        "Approved",
        "AutoApproved",
        "PendingCompletion",
        "Completed",
        "Denied",
        "Error",
    ],
    typing.Any,
]
