# This file was auto-generated by Fern from our API Definition.

import typing

CaseTrigger = typing.Union[
    typing.Literal[
        "Submit",
        "Verify",
        "RequestReview",
        "Assign",
        "RequestResponse",
        "Escalate",
        "Approve",
        "AutoApprove",
        "RequestCompletion",
        "Complete",
        "Deny",
        "Error",
    ],
    typing.Any,
]
