# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class CaseListSummary(UniversalBaseModel):
    """
    Pagination and totals for a case list response.
    """

    total_records: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="totalRecords"),
        pydantic.Field(alias="totalRecords", description="The total number of matching cases."),
    ]
    """
    The total number of matching cases.
    """

    total_amount: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="totalAmount"),
        pydantic.Field(
            alias="totalAmount", description="Not used for cases; returned as part of the shared list envelope."
        ),
    ]
    """
    Not used for cases; returned as part of the shared list envelope.
    """

    total_net_amount: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="totalNetAmount"),
        pydantic.Field(
            alias="totalNetAmount", description="Not used for cases; returned as part of the shared list envelope."
        ),
    ]
    """
    Not used for cases; returned as part of the shared list envelope.
    """

    total_pages: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="totalPages"),
        pydantic.Field(alias="totalPages", description="The total number of pages."),
    ]
    """
    The total number of pages.
    """

    page_size: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="pageSize"),
        pydantic.Field(alias="pageSize", description="The number of records per page."),
    ]
    """
    The number of records per page.
    """

    pageidentifier: typing.Optional[str] = pydantic.Field(default=None)
    """
    An opaque page identifier, when present.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
