# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .bank_verification_metadata import BankVerificationMetadata
from .review_decision_metadata import ReviewDecisionMetadata


class CaseMetadata(UniversalBaseModel):
    """
    Case metadata, populated as the case progresses. Null until verification completes.
    """

    verification: typing.Optional[BankVerificationMetadata] = pydantic.Field(default=None)
    """
    The verification outcome. Null until verification finishes.
    """

    review_decision: typing_extensions.Annotated[
        typing.Optional[ReviewDecisionMetadata],
        FieldMetadata(alias="reviewDecision"),
        pydantic.Field(alias="reviewDecision", description="The reviewer's decision, when one has been made."),
    ] = None
    """
    The reviewer's decision, when one has been made.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
