# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .attachment_response import AttachmentResponse
from .bank_account_change_parameters import BankAccountChangeParameters
from .case_metadata import CaseMetadata
from .case_state import CaseState
from .case_type import CaseType
from .org_ref import OrgRef
from .paypoint_ref import PaypointRef
from .state_transition_response import StateTransitionResponse
from .user_ref import UserRef


class CaseResponse(UniversalBaseModel):
    """
    A bank-account-change case.
    """

    uuid_: typing_extensions.Annotated[
        str, FieldMetadata(alias="uuid"), pydantic.Field(alias="uuid", description="The case's unique identifier.")
    ]
    """
    The case's unique identifier.
    """

    state: CaseState
    case_type: typing_extensions.Annotated[CaseType, FieldMetadata(alias="caseType"), pydantic.Field(alias="caseType")]
    parameters: BankAccountChangeParameters
    org_id: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="orgId"),
        pydantic.Field(alias="orgId", description="The organization that owns the case."),
    ]
    """
    The organization that owns the case.
    """

    paypoint_id: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="paypointId"),
        pydantic.Field(alias="paypointId", description="The paypoint the case applies to."),
    ]
    """
    The paypoint the case applies to.
    """

    schedule_for: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="scheduleFor"),
        pydantic.Field(
            alias="scheduleFor", description="When the change is scheduled to run. Null when not scheduled."
        ),
    ] = None
    """
    When the change is scheduled to run. Null when not scheduled.
    """

    created_at: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="createdAt"),
        pydantic.Field(alias="createdAt", description="When the case was created."),
    ]
    """
    When the case was created.
    """

    updated_at: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="updatedAt"),
        pydantic.Field(alias="updatedAt", description="When the case was last updated."),
    ]
    """
    When the case was last updated.
    """

    created_by: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="createdBy"),
        pydantic.Field(
            alias="createdBy",
            description="The numeric id of the user who created the case. `0` when created by a server-side integration.",
        ),
    ]
    """
    The numeric id of the user who created the case. `0` when created by a server-side integration.
    """

    assignee_id: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="assigneeId"),
        pydantic.Field(
            alias="assigneeId", description="The numeric id of the assigned reviewer. Null when unassigned."
        ),
    ] = None
    """
    The numeric id of the assigned reviewer. Null when unassigned.
    """

    last_reviewed_by_id: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="lastReviewedById"),
        pydantic.Field(
            alias="lastReviewedById", description="The numeric id of the last reviewer. Null when not yet reviewed."
        ),
    ] = None
    """
    The numeric id of the last reviewer. Null when not yet reviewed.
    """

    state_history: typing_extensions.Annotated[
        typing.List[StateTransitionResponse],
        FieldMetadata(alias="stateHistory"),
        pydantic.Field(alias="stateHistory", description="The ordered history of state transitions."),
    ]
    """
    The ordered history of state transitions.
    """

    attachments: typing.List[AttachmentResponse] = pydantic.Field()
    """
    Files attached to the case.
    """

    room_id: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="roomId"),
        pydantic.Field(alias="roomId", description="The id of the message room for the case. Null until provisioned."),
    ] = None
    """
    The id of the message room for the case. Null until provisioned.
    """

    metadata: typing.Optional[CaseMetadata] = pydantic.Field(default=None)
    """
    Case metadata, including the verification outcome. Null until verification completes.
    """

    org: typing.Optional[OrgRef] = pydantic.Field(default=None)
    """
    The resolved organization. Null when not enriched.
    """

    paypoint: typing.Optional[PaypointRef] = pydantic.Field(default=None)
    """
    The resolved paypoint. Null when not enriched.
    """

    created_by_user: typing_extensions.Annotated[
        typing.Optional[UserRef],
        FieldMetadata(alias="createdByUser"),
        pydantic.Field(
            alias="createdByUser",
            description="The resolved creator. Null when created by a server-side integration or not enriched.",
        ),
    ] = None
    """
    The resolved creator. Null when created by a server-side integration or not enriched.
    """

    assignee: typing.Optional[UserRef] = pydantic.Field(default=None)
    """
    The resolved assigned reviewer. Null when unassigned.
    """

    last_reviewed_by: typing_extensions.Annotated[
        typing.Optional[UserRef],
        FieldMetadata(alias="lastReviewedBy"),
        pydantic.Field(alias="lastReviewedBy", description="The resolved last reviewer. Null when not yet reviewed."),
    ] = None
    """
    The resolved last reviewer. Null when not yet reviewed.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
