# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .customer_id import CustomerId
from .customer_number_nullable import CustomerNumberNullable
from .customer_query_records_customer_consent import CustomerQueryRecordsCustomerConsent
from .customer_status import CustomerStatus
from .customer_summary_record import CustomerSummaryRecord
from .dbaname import Dbaname
from .email import Email
from .entrypointfield import Entrypointfield
from .external_paypoint_id import ExternalPaypointId
from .identifierfields import Identifierfields
from .legalname import Legalname
from .method_query_records import MethodQueryRecords
from .mfa import Mfa
from .mfa_mode import MfaMode
from .org_parent_id import OrgParentId
from .org_parent_name import OrgParentName
from .page_identifier import PageIdentifier
from .shippingaddress import Shippingaddress
from .shippingaddressadditional import Shippingaddressadditional
from .shippingcity import Shippingcity
from .shippingcountry import Shippingcountry
from .shippingstate import Shippingstate
from .shippingzip import Shippingzip
from .subscription_query_records import SubscriptionQueryRecords
from .timezone import Timezone


class CustomerQueryRecords(UniversalBaseModel):
    customer_id: typing_extensions.Annotated[
        typing.Optional[CustomerId], FieldMetadata(alias="customerId"), pydantic.Field(alias="customerId")
    ] = None
    customer_number: typing_extensions.Annotated[
        typing.Optional[CustomerNumberNullable],
        FieldMetadata(alias="customerNumber"),
        pydantic.Field(alias="customerNumber"),
    ] = None
    customer_username: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="customerUsername"),
        pydantic.Field(alias="customerUsername", description="Username for customer."),
    ] = None
    customer_status: typing_extensions.Annotated[
        typing.Optional[CustomerStatus], FieldMetadata(alias="customerStatus"), pydantic.Field(alias="customerStatus")
    ] = None
    company: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="Company"),
        pydantic.Field(alias="Company", description="Company name."),
    ] = None
    firstname: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="Firstname"),
        pydantic.Field(alias="Firstname", description="Customer first name."),
    ] = None
    lastname: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="Lastname"),
        pydantic.Field(alias="Lastname", description="Customer last name."),
    ] = None
    phone: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="Phone"),
        pydantic.Field(alias="Phone", description="Customer phone number."),
    ] = None
    email: typing_extensions.Annotated[
        typing.Optional[Email],
        FieldMetadata(alias="Email"),
        pydantic.Field(alias="Email", description="Customer email address."),
    ] = None
    address: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="Address"),
        pydantic.Field(alias="Address", description="Customer address."),
    ] = None
    address_1: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="Address1"),
        pydantic.Field(alias="Address1", description="Additional line for customer address."),
    ] = None
    city: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="City"), pydantic.Field(alias="City", description="Customer city.")
    ] = None
    state: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="State"), pydantic.Field(alias="State", description="Customer state.")
    ] = None
    zip: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="Zip"),
        pydantic.Field(alias="Zip", description="Customer postal code."),
    ] = None
    country: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="Country"),
        pydantic.Field(alias="Country", description="Customer country."),
    ] = None
    shipping_address: typing_extensions.Annotated[
        typing.Optional[Shippingaddress],
        FieldMetadata(alias="ShippingAddress"),
        pydantic.Field(alias="ShippingAddress"),
    ] = None
    shipping_address_1: typing_extensions.Annotated[
        typing.Optional[Shippingaddressadditional],
        FieldMetadata(alias="ShippingAddress1"),
        pydantic.Field(alias="ShippingAddress1"),
    ] = None
    shipping_city: typing_extensions.Annotated[
        typing.Optional[Shippingcity], FieldMetadata(alias="ShippingCity"), pydantic.Field(alias="ShippingCity")
    ] = None
    shipping_state: typing_extensions.Annotated[
        typing.Optional[Shippingstate], FieldMetadata(alias="ShippingState"), pydantic.Field(alias="ShippingState")
    ] = None
    shipping_zip: typing_extensions.Annotated[
        typing.Optional[Shippingzip], FieldMetadata(alias="ShippingZip"), pydantic.Field(alias="ShippingZip")
    ] = None
    shipping_country: typing_extensions.Annotated[
        typing.Optional[Shippingcountry],
        FieldMetadata(alias="ShippingCountry"),
        pydantic.Field(alias="ShippingCountry"),
    ] = None
    balance: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="Balance"),
        pydantic.Field(alias="Balance", description="Customer balance."),
    ] = None
    time_zone: typing_extensions.Annotated[
        typing.Optional[Timezone], FieldMetadata(alias="TimeZone"), pydantic.Field(alias="TimeZone")
    ] = None
    mfa: typing_extensions.Annotated[typing.Optional[Mfa], FieldMetadata(alias="MFA"), pydantic.Field(alias="MFA")] = (
        None
    )
    mfa_mode: typing_extensions.Annotated[
        typing.Optional[MfaMode], FieldMetadata(alias="MFAMode"), pydantic.Field(alias="MFAMode")
    ] = None
    sn_provider: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="snProvider"),
        pydantic.Field(
            alias="snProvider",
            description="Social network linked to customer. Possible values:\n- `facebook`\n- `google`\n- `twitter`\n- `microsoft`",
        ),
    ] = None
    sn_identifier: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="snIdentifier"),
        pydantic.Field(alias="snIdentifier", description="Identifier or token for customer in linked social network."),
    ] = None
    sn_data: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="snData"),
        pydantic.Field(
            alias="snData", description="Additional data provided by the social network related to the customer."
        ),
    ] = None
    last_updated: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="LastUpdated"),
        pydantic.Field(alias="LastUpdated", description="Date and time of last update."),
    ] = None
    created: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="Created"),
        pydantic.Field(alias="Created", description="Date and time created."),
    ] = None
    additional_fields: typing_extensions.Annotated[
        typing.Optional[typing.Dict[str, str]],
        FieldMetadata(alias="AdditionalFields"),
        pydantic.Field(alias="AdditionalFields", description="List of additional custom fields in format key:value."),
    ] = None
    identifier_fields: typing_extensions.Annotated[
        typing.Optional[Identifierfields],
        FieldMetadata(alias="IdentifierFields"),
        pydantic.Field(alias="IdentifierFields"),
    ] = None
    subscriptions: typing_extensions.Annotated[
        typing.Optional[typing.List[SubscriptionQueryRecords]],
        FieldMetadata(alias="Subscriptions"),
        pydantic.Field(alias="Subscriptions", description="List of subscriptions associated to the customer."),
    ] = None
    stored_methods: typing_extensions.Annotated[
        typing.Optional[typing.List[MethodQueryRecords]],
        FieldMetadata(alias="StoredMethods"),
        pydantic.Field(alias="StoredMethods", description="List of payment methods associated to the customer."),
    ] = None
    customer_summary: typing_extensions.Annotated[
        typing.Optional[CustomerSummaryRecord],
        FieldMetadata(alias="customerSummary"),
        pydantic.Field(alias="customerSummary"),
    ] = None
    paypoint_legalname: typing_extensions.Annotated[
        typing.Optional[Legalname],
        FieldMetadata(alias="PaypointLegalname"),
        pydantic.Field(alias="PaypointLegalname", description="Paypoint legal name."),
    ] = None
    paypoint_dbaname: typing_extensions.Annotated[
        typing.Optional[Dbaname],
        FieldMetadata(alias="PaypointDbaname"),
        pydantic.Field(alias="PaypointDbaname", description="Paypoint DBA name."),
    ] = None
    parent_org_name: typing_extensions.Annotated[
        typing.Optional[OrgParentName], FieldMetadata(alias="ParentOrgName"), pydantic.Field(alias="ParentOrgName")
    ] = None
    parent_org_id: typing_extensions.Annotated[
        typing.Optional[OrgParentId], FieldMetadata(alias="ParentOrgId"), pydantic.Field(alias="ParentOrgId")
    ] = None
    paypoint_entryname: typing_extensions.Annotated[
        typing.Optional[Entrypointfield],
        FieldMetadata(alias="PaypointEntryname"),
        pydantic.Field(alias="PaypointEntryname"),
    ] = None
    pageidentifier: typing.Optional[PageIdentifier] = None
    external_paypoint_id: typing_extensions.Annotated[
        typing.Optional[ExternalPaypointId],
        FieldMetadata(alias="externalPaypointID"),
        pydantic.Field(alias="externalPaypointID"),
    ] = None
    customer_consent: typing_extensions.Annotated[
        typing.Optional[CustomerQueryRecordsCustomerConsent],
        FieldMetadata(alias="customerConsent"),
        pydantic.Field(alias="customerConsent"),
    ] = None
    customer_portal: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="customerPortal"), pydantic.Field(alias="customerPortal")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
