# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class DeviceChallengeData(UniversalBaseModel):
    """
    The issued activation code and the time it expires.
    """

    code: str = pydantic.Field()
    """
    The 6-digit verification code the operator enters on the device's
    terminal to activate it. It can start with leading zeros, so keep it as
    a string.
    """

    expires_at: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="expiresAt"),
        pydantic.Field(
            alias="expiresAt",
            description="UTC time when the code expires, in ISO-8601 round-trip format. A code is\nvalid for 5 minutes after it's issued.",
        ),
    ]
    """
    UTC time when the code expires, in ISO-8601 round-trip format. A code is
    valid for 5 minutes after it's issued.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
