# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class EntitiesAssigned(UniversalBaseModel):
    """
    Counts of entities the profile is assigned to. Any non-zero count locks the
    profile from deletion in the Payabli Portal.
    """

    organizations: int = pydantic.Field()
    """
    Number of organizations the profile is assigned to.
    """

    paypoints: int = pydantic.Field()
    """
    Number of paypoints the profile is assigned to.
    """

    templates: int = pydantic.Field()
    """
    Number of boarding templates the profile is assigned to.
    """

    applications: int = pydantic.Field()
    """
    Number of boarding applications the profile is assigned to.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
