# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .billing_entity import BillingEntity
from .collection_schedule_value import CollectionScheduleValue
from .fee_type_value import FeeTypeValue
from .passthrough_value import PassthroughValue


class FeeSchedule(UniversalBaseModel):
    """
    A fee schedule attached to a billable event. Flat and interchange-plus
    schedules share this shape; `feeType` is the discriminator.
    """

    id: int = pydantic.Field()
    """
    Fee schedule identifier.
    """

    value: float = pydantic.Field()
    """
    The flat-fee component of the fee, for example `0.30`.
    """

    rate: float = pydantic.Field()
    """
    The percentage-rate component of the fee, for example `2.9`.
    """

    passthrough: PassthroughValue
    payor: typing.Optional[BillingEntity] = pydantic.Field(default=None)
    """
    Entity responsible for paying this fee. `null` when not set.
    """

    collector: typing.Optional[BillingEntity] = pydantic.Field(default=None)
    """
    Entity that collects this fee. `null` when not set.
    """

    overflow_payor: typing_extensions.Annotated[
        typing.Optional[BillingEntity],
        FieldMetadata(alias="overflowPayor"),
        pydantic.Field(
            alias="overflowPayor",
            description="Fallback payor used when the primary payor can't cover the fee. `null`\nwhen not set.",
        ),
    ] = None
    """
    Fallback payor used when the primary payor can't cover the fee. `null`
    when not set.
    """

    overflow_collection_schedule: typing_extensions.Annotated[
        typing.Optional[CollectionScheduleValue],
        FieldMetadata(alias="overflowCollectionSchedule"),
        pydantic.Field(
            alias="overflowCollectionSchedule",
            description="Collection cadence for the overflow payor. `null` when not set.",
        ),
    ] = None
    """
    Collection cadence for the overflow payor. `null` when not set.
    """

    minimum_total: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="minimumTotal"),
        pydantic.Field(
            alias="minimumTotal", description="Floor on the combined fee (rate + flat value) for this schedule."
        ),
    ] = None
    """
    Floor on the combined fee (rate + flat value) for this schedule.
    """

    maximum_total: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="maximumTotal"),
        pydantic.Field(
            alias="maximumTotal", description="Ceiling on the combined fee (rate + flat value) for this schedule."
        ),
    ] = None
    """
    Ceiling on the combined fee (rate + flat value) for this schedule.
    """

    effective_date: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="effectiveDate"),
        pydantic.Field(
            alias="effectiveDate",
            description="When this schedule starts applying. Drives ordering when an event has\nmultiple schedules.",
        ),
    ]
    """
    When this schedule starts applying. Drives ordering when an event has
    multiple schedules.
    """

    expiration_date: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="expirationDate"),
        pydantic.Field(
            alias="expirationDate", description="When this schedule stops applying. `null` means no end date."
        ),
    ] = None
    """
    When this schedule stops applying. `null` means no end date.
    """

    created_at: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="createdAt"),
        pydantic.Field(alias="createdAt", description="When this schedule was created."),
    ]
    """
    When this schedule was created.
    """

    updated_at: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="updatedAt"),
        pydantic.Field(alias="updatedAt", description="When this schedule was last updated."),
    ]
    """
    When this schedule was last updated.
    """

    created_by: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="createdBy"),
        pydantic.Field(
            alias="createdBy",
            description='Identifier of the schedule\'s creator. Surfaces in the Payabli Portal as\n"Configuration Owner" — informational, not a permission boundary.',
        ),
    ]
    """
    Identifier of the schedule's creator. Surfaces in the Payabli Portal as
    "Configuration Owner" — informational, not a permission boundary.
    """

    collection_schedule: typing_extensions.Annotated[
        CollectionScheduleValue, FieldMetadata(alias="collectionSchedule"), pydantic.Field(alias="collectionSchedule")
    ]
    bill_date: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="billDate"),
        pydantic.Field(
            alias="billDate", description="Day of the month a monthly bill is applied, when set. `null` otherwise."
        ),
    ] = None
    """
    Day of the month a monthly bill is applied, when set. `null` otherwise.
    """

    override_fee_schedule_id: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="overrideFeeScheduleId"),
        pydantic.Field(
            alias="overrideFeeScheduleId",
            description="Identifier of another fee schedule this one overrides. `null` otherwise.",
        ),
    ] = None
    """
    Identifier of another fee schedule this one overrides. `null` otherwise.
    """

    fee_type: typing_extensions.Annotated[FeeTypeValue, FieldMetadata(alias="feeType"), pydantic.Field(alias="feeType")]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
