# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class FrequencyList(UniversalBaseModel):
    annually: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Enable or disable frequency
    """

    every_2_weeks: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="every2Weeks"),
        pydantic.Field(alias="every2Weeks", description="Enable or disable frequency"),
    ] = None
    every_3_months: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="every3Months"),
        pydantic.Field(alias="every3Months", description="Enable or disable frequency"),
    ] = None
    every_6_months: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="every6Months"),
        pydantic.Field(alias="every6Months", description="Enable or disable frequency"),
    ] = None
    monthly: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Enable or disable frequency
    """

    onetime: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Enable or disable frequency
    """

    weekly: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Enable or disable frequency
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
