# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .customer_id import CustomerId
from .customer_number_nullable import CustomerNumberNullable
from .customer_summary_record import CustomerSummaryRecord
from .dbaname import Dbaname
from .email import Email
from .external_paypoint_id import ExternalPaypointId
from .identifierfields import Identifierfields
from .legalname import Legalname
from .method_query_records import MethodQueryRecords
from .org_parent_name import OrgParentName
from .page_identifier import PageIdentifier
from .shippingaddress import Shippingaddress
from .shippingaddressadditional import Shippingaddressadditional
from .shippingcity import Shippingcity
from .shippingcountry import Shippingcountry
from .shippingstate import Shippingstate
from .shippingzip import Shippingzip
from .subscription_query_records import SubscriptionQueryRecords


class GetMethodResponseResponseDataCustomersItem(UniversalBaseModel):
    """
    The customer record that owns the stored payment method.
    """

    additional_fields: typing_extensions.Annotated[
        typing.Optional[typing.Dict[str, str]],
        FieldMetadata(alias="additionalFields"),
        pydantic.Field(alias="additionalFields", description="List of additional custom fields in format key:value."),
    ] = None
    """
    List of additional custom fields in format key:value.
    """

    address: typing.Optional[str] = pydantic.Field(default=None)
    """
    Customer address.
    """

    address_1: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="address1"),
        pydantic.Field(alias="address1", description="Additional line for customer address."),
    ] = None
    """
    Additional line for customer address.
    """

    balance: typing.Optional[float] = pydantic.Field(default=None)
    """
    Customer's current balance
    """

    city: typing.Optional[str] = pydantic.Field(default=None)
    """
    Customer city.
    """

    company: typing.Optional[str] = pydantic.Field(default=None)
    """
    Company name.
    """

    country: typing.Optional[str] = pydantic.Field(default=None)
    """
    Customer country.
    """

    created: typing.Optional[dt.datetime] = pydantic.Field(default=None)
    """
    Creation timestamp
    """

    customer_consent: typing_extensions.Annotated[
        typing.Optional[typing.Dict[str, typing.Any]],
        FieldMetadata(alias="customerConsent"),
        pydantic.Field(alias="customerConsent", description="Customer consent information"),
    ] = None
    """
    Customer consent information
    """

    customer_events: typing_extensions.Annotated[
        typing.Optional[typing.List[typing.Any]],
        FieldMetadata(alias="customerEvents"),
        pydantic.Field(alias="customerEvents", description="Events recorded for the customer."),
    ] = None
    """
    Events recorded for the customer.
    """

    customer_id: typing_extensions.Annotated[
        typing.Optional[CustomerId], FieldMetadata(alias="customerId"), pydantic.Field(alias="customerId")
    ] = None
    customer_number: typing_extensions.Annotated[
        typing.Optional[CustomerNumberNullable],
        FieldMetadata(alias="customerNumber"),
        pydantic.Field(alias="customerNumber"),
    ] = None
    customer_portal: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="customerPortal"), pydantic.Field(alias="customerPortal")
    ] = None
    customer_status: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="customerStatus"),
        pydantic.Field(alias="customerStatus", description="Status code for the customer"),
    ] = None
    """
    Status code for the customer
    """

    customer_summary: typing_extensions.Annotated[
        typing.Optional[CustomerSummaryRecord],
        FieldMetadata(alias="customerSummary"),
        pydantic.Field(alias="customerSummary"),
    ] = None
    customer_username: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="customerUsername"),
        pydantic.Field(alias="customerUsername", description="Username of the customer"),
    ] = None
    """
    Username of the customer
    """

    email: typing.Optional[Email] = pydantic.Field(default=None)
    """
    Customer email address.
    """

    external_paypoint_id: typing_extensions.Annotated[
        typing.Optional[ExternalPaypointId],
        FieldMetadata(alias="externalPaypointID"),
        pydantic.Field(alias="externalPaypointID"),
    ] = None
    firstname: typing.Optional[str] = pydantic.Field(default=None)
    """
    Customer first name.
    """

    identifier_fields: typing_extensions.Annotated[
        typing.Optional[Identifierfields],
        FieldMetadata(alias="identifierFields"),
        pydantic.Field(alias="identifierFields"),
    ] = None
    lastname: typing.Optional[str] = pydantic.Field(default=None)
    """
    Customer last name.
    """

    last_updated: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="lastUpdated"),
        pydantic.Field(alias="lastUpdated", description="Last update timestamp"),
    ] = None
    """
    Last update timestamp
    """

    mfa: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Multi-factor authentication status
    """

    mfa_mode: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="mfaMode"),
        pydantic.Field(alias="mfaMode", description="MFA mode setting"),
    ] = None
    """
    MFA mode setting
    """

    pageindentifier: typing.Optional[PageIdentifier] = None
    parent_org_id: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="parentOrgId"),
        pydantic.Field(alias="parentOrgId", description="Parent organization ID"),
    ] = None
    """
    Parent organization ID
    """

    parent_org_name: typing_extensions.Annotated[
        typing.Optional[OrgParentName], FieldMetadata(alias="parentOrgName"), pydantic.Field(alias="parentOrgName")
    ] = None
    paypoint_dbaname: typing_extensions.Annotated[
        typing.Optional[Dbaname], FieldMetadata(alias="paypointDbaname"), pydantic.Field(alias="paypointDbaname")
    ] = None
    paypoint_entryname: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="paypointEntryname"),
        pydantic.Field(alias="paypointEntryname", description="The paypoint entryname the customer is associated with"),
    ] = None
    """
    The paypoint entryname the customer is associated with
    """

    paypoint_legalname: typing_extensions.Annotated[
        typing.Optional[Legalname], FieldMetadata(alias="paypointLegalname"), pydantic.Field(alias="paypointLegalname")
    ] = None
    phone: typing.Optional[str] = pydantic.Field(default=None)
    """
    Customer phone number.
    """

    shipping_address: typing_extensions.Annotated[
        typing.Optional[Shippingaddress],
        FieldMetadata(alias="shippingAddress"),
        pydantic.Field(alias="shippingAddress"),
    ] = None
    shipping_address_1: typing_extensions.Annotated[
        typing.Optional[Shippingaddressadditional],
        FieldMetadata(alias="shippingAddress1"),
        pydantic.Field(alias="shippingAddress1"),
    ] = None
    shipping_city: typing_extensions.Annotated[
        typing.Optional[Shippingcity], FieldMetadata(alias="shippingCity"), pydantic.Field(alias="shippingCity")
    ] = None
    shipping_country: typing_extensions.Annotated[
        typing.Optional[Shippingcountry],
        FieldMetadata(alias="shippingCountry"),
        pydantic.Field(alias="shippingCountry"),
    ] = None
    shipping_state: typing_extensions.Annotated[
        typing.Optional[Shippingstate], FieldMetadata(alias="shippingState"), pydantic.Field(alias="shippingState")
    ] = None
    shipping_zip: typing_extensions.Annotated[
        typing.Optional[Shippingzip], FieldMetadata(alias="shippingZip"), pydantic.Field(alias="shippingZip")
    ] = None
    sn_data: typing_extensions.Annotated[
        typing.Optional[typing.Dict[str, typing.Any]],
        FieldMetadata(alias="snData"),
        pydantic.Field(alias="snData", description="Social network data"),
    ] = None
    """
    Social network data
    """

    sn_identifier: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="snIdentifier"),
        pydantic.Field(alias="snIdentifier", description="Social network identifier"),
    ] = None
    """
    Social network identifier
    """

    sn_provider: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="snProvider"),
        pydantic.Field(alias="snProvider", description="Social network provider"),
    ] = None
    """
    Social network provider
    """

    state: typing.Optional[str] = pydantic.Field(default=None)
    """
    Customer state.
    """

    stored_methods: typing_extensions.Annotated[
        typing.Optional[typing.List[MethodQueryRecords]],
        FieldMetadata(alias="storedMethods"),
        pydantic.Field(alias="storedMethods", description="List of payment methods associated to the customer"),
    ] = None
    """
    List of payment methods associated to the customer
    """

    subscriptions: typing.Optional[typing.List[SubscriptionQueryRecords]] = pydantic.Field(default=None)
    """
    List of subscriptions associated to the customer
    """

    time_zone: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="timeZone"),
        pydantic.Field(alias="timeZone", description="Customer's timezone"),
    ] = None
    """
    Customer's timezone
    """

    zip: typing.Optional[str] = pydantic.Field(default=None)
    """
    Customer postal code.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
