# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .bin_data import BinData
from .descriptor import Descriptor
from .holdername import Holdername
from .last_modified import LastModified
from .maskedaccount import Maskedaccount


class MethodQueryRecords(UniversalBaseModel):
    id_pmethod: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="IdPmethod"),
        pydantic.Field(alias="IdPmethod", description="Method internal ID"),
    ] = None
    method: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="Method"),
        pydantic.Field(alias="Method", description="Type of payment vehicle: **ach** or **card**"),
    ] = None
    descriptor: typing_extensions.Annotated[
        typing.Optional[Descriptor], FieldMetadata(alias="Descriptor"), pydantic.Field(alias="Descriptor")
    ] = None
    masked_account: typing_extensions.Annotated[
        typing.Optional[Maskedaccount], FieldMetadata(alias="MaskedAccount"), pydantic.Field(alias="MaskedAccount")
    ] = None
    exp_date: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="ExpDate"),
        pydantic.Field(
            alias="ExpDate", description="Expiration date associated to the method (only for card) in format MMYY."
        ),
    ] = None
    holder_name: typing_extensions.Annotated[
        typing.Optional[Holdername], FieldMetadata(alias="HolderName"), pydantic.Field(alias="HolderName")
    ] = None
    ach_sec_code: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="AchSecCode"),
        pydantic.Field(alias="AchSecCode", description="Standard Entry Class (SEC) code for the ACH transaction."),
    ] = None
    ach_holder_type: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="AchHolderType"),
        pydantic.Field(alias="AchHolderType", description="Bank accountholder type: `personal` or `business`."),
    ] = None
    is_validated_ach: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="IsValidatedACH"),
        pydantic.Field(alias="IsValidatedACH", description="Whether the ACH account has been validated."),
    ] = None
    bin: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="BIN"),
        pydantic.Field(alias="BIN", description="The bank identification number (BIN). Null when method is ACH."),
    ] = None
    bin_data: typing_extensions.Annotated[
        typing.Optional[BinData], FieldMetadata(alias="binData"), pydantic.Field(alias="binData")
    ] = None
    aba: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="ABA"),
        pydantic.Field(alias="ABA", description="Bank routing number."),
    ] = None
    postal_code: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="PostalCode"),
        pydantic.Field(alias="PostalCode", description="The payment method postal code."),
    ] = None
    method_type: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="MethodType"),
        pydantic.Field(alias="MethodType", description="The payment method's token type."),
    ] = None
    wallet_type: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="WalletType"),
        pydantic.Field(alias="WalletType", description="Digital wallet type if applicable."),
    ] = None
    last_updated: typing_extensions.Annotated[
        typing.Optional[LastModified],
        FieldMetadata(alias="LastUpdated"),
        pydantic.Field(alias="LastUpdated", description="Date of last update"),
    ] = None
    card_updated_on: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="CardUpdatedOn"),
        pydantic.Field(alias="CardUpdatedOn", description="Date and time the card was last updated."),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
