# This file was auto-generated by Fern from our API Definition.

import typing

OnCreate = typing.List[str]
"""
Actions to take when the application is created. The only currently
supported option is `submitApplication`. Use this when you have collected
eSignature elsewhere or are adding additional locations for an applicant,
or when you want to submit an application via API with one call without
using the hosted boarding UI or embedded boarding components. Pass the
value as an array, for example `["submitApplication"]`.
"""
