# This file was auto-generated by Fern from our API Definition.

PassthroughValue = int
"""
Whether the fee is passed through to the customer, and which type,
serialized as an integer: `0` None, `1` Surcharge, `2` Convenience,
`3` Service.
"""
