# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .device import Device
from .pay_method_cloud_method import PayMethodCloudMethod


class PayMethodCloud(UniversalBaseModel):
    device: typing.Optional[Device] = None
    method: PayMethodCloudMethod = pydantic.Field()
    """
    Method to use for the transaction. For cloud device transactions, the method is `cloud`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
