# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class PayabliApiResponseError400Tokenization(UniversalBaseModel):
    response_text: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="responseText")] = (
        pydantic.Field(default=None)
    )
    """
    Response text for request. Explains the reason for the error.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
