# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .is_success import IsSuccess
from .ocr_response_data import OcrResponseData
from .response_text import ResponseText
from .responsecode import Responsecode


class PayabliApiResponseOcr(UniversalBaseModel):
    is_success: typing_extensions.Annotated[
        IsSuccess, FieldMetadata(alias="isSuccess"), pydantic.Field(alias="isSuccess")
    ]
    response_text: typing_extensions.Annotated[
        ResponseText, FieldMetadata(alias="responseText"), pydantic.Field(alias="responseText")
    ]
    response_code: typing_extensions.Annotated[
        Responsecode, FieldMetadata(alias="responseCode"), pydantic.Field(alias="responseCode")
    ]
    response_data: typing_extensions.Annotated[
        typing.Optional[OcrResponseData],
        FieldMetadata(alias="responseData"),
        pydantic.Field(alias="responseData", description="Details of the OCR processing result"),
    ] = None
    """
    Details of the OCR processing result
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
