# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .additional_data import AdditionalData
from .page_content import PageContent
from .page_identifier import PageIdentifier
from .page_setting import PageSetting
from .payabli_credentials import PayabliCredentials
from .receipt_content import ReceiptContent
from .subdomain import Subdomain


class PayabliPages(UniversalBaseModel):
    additional_data: typing_extensions.Annotated[
        typing.Optional[AdditionalData], FieldMetadata(alias="AdditionalData"), pydantic.Field(alias="AdditionalData")
    ] = None
    credentials: typing_extensions.Annotated[
        typing.Optional[typing.List[PayabliCredentials]],
        FieldMetadata(alias="Credentials"),
        pydantic.Field(
            alias="Credentials", description="Array of credential objects with active services for the page"
        ),
    ] = None
    """
    Array of credential objects with active services for the page
    """

    last_access: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="LastAccess"),
        pydantic.Field(alias="LastAccess", description="Timestamp of last access to page structure"),
    ] = None
    """
    Timestamp of last access to page structure
    """

    page_content: typing_extensions.Annotated[
        typing.Optional[PageContent],
        FieldMetadata(alias="PageContent"),
        pydantic.Field(alias="PageContent", description="Sections of page"),
    ] = None
    """
    Sections of page
    """

    page_identifier: typing_extensions.Annotated[
        typing.Optional[PageIdentifier], FieldMetadata(alias="pageIdentifier"), pydantic.Field(alias="pageIdentifier")
    ] = None
    page_settings: typing_extensions.Annotated[
        typing.Optional[PageSetting],
        FieldMetadata(alias="PageSettings"),
        pydantic.Field(alias="PageSettings", description="Settings of page"),
    ] = None
    """
    Settings of page
    """

    published: typing.Optional[int] = pydantic.Field(default=None)
    """
    Flag indicating if page is active to accept payments. `0` for false, `1` for true.
    """

    receipt_content: typing_extensions.Annotated[
        typing.Optional[ReceiptContent],
        FieldMetadata(alias="ReceiptContent"),
        pydantic.Field(alias="ReceiptContent", description="Sections of payment receipt"),
    ] = None
    """
    Sections of payment receipt
    """

    subdomain: typing_extensions.Annotated[
        typing.Optional[Subdomain],
        FieldMetadata(alias="Subdomain"),
        pydantic.Field(alias="Subdomain", description="Page identifier. Must be unique in platform."),
    ] = None
    """
    Page identifier. Must be unique in platform.
    """

    total_amount: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="totalAmount"),
        pydantic.Field(alias="totalAmount", description="Total amount to pay in this page"),
    ] = None
    """
    Total amount to pay in this page
    """

    validation_code: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="validationCode"),
        pydantic.Field(
            alias="validationCode", description="Base64 encoded image of CAPTCHA associated to this page load"
        ),
    ] = None
    """
    Base64 encoded image of CAPTCHA associated to this page load
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
