# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class PayabliAccessTokenResponse(UniversalBaseModel):
    """
    Successful response from the token endpoint. Returns the access token, its lifetime, and any state echoed from the request.
    """

    token_type: str = pydantic.Field()
    """
    The token type. Send the access token in the `Authorization` header as `Bearer <access_token>`.
    """

    access_token: str = pydantic.Field()
    """
    The access token to send on subsequent API calls.
    """

    expires_in: int = pydantic.Field()
    """
    The token's lifetime in seconds. Request a new token when it expires.
    """

    state: typing.Optional[str] = pydantic.Field(default=None)
    """
    The opaque value sent in the request, echoed back. Present only when you send `state` in the request.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
