# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class PayabliErrorBodyResponseData(UniversalBaseModel):
    """
    Object with detailed error context.
    """

    explanation: typing.Optional[str] = pydantic.Field(default=None)
    """
    Human-readable explanation of what happened.
    """

    todo_action: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="todoAction"),
        pydantic.Field(alias="todoAction", description="Suggested resolution."),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
