# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .bill_pay_out_data import BillPayOutData
from .created_at import CreatedAt
from .dbaname import Dbaname
from .entrypage_id import EntrypageId
from .entrypointfield import Entrypointfield
from .external_paypoint_id import ExternalPaypointId
from .general_events import GeneralEvents
from .last_modified import LastModified
from .legalname import Legalname
from .netamountnullable import Netamountnullable
from .org_parent_id import OrgParentId
from .org_parent_name import OrgParentName
from .paypoint_id import PaypointId
from .query_payment_data import QueryPaymentData
from .source import Source
from .vendor_query_record import VendorQueryRecord


class PayoutSubscriptionQueryRecordPascal(UniversalBaseModel):
    id_out_subscription: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="IdOutSubscription"),
        pydantic.Field(alias="IdOutSubscription", description="The payout subscription's ID."),
    ] = None
    status: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="Status"),
        pydantic.Field(alias="Status", description="The payout subscription's status.\n- 0: Paused\n- 1: Active"),
    ] = None
    events: typing_extensions.Annotated[
        typing.Optional[typing.List[GeneralEvents]],
        FieldMetadata(alias="Events"),
        pydantic.Field(alias="Events", description="Events associated with the payout subscription."),
    ] = None
    vendor: typing_extensions.Annotated[
        typing.Optional[VendorQueryRecord], FieldMetadata(alias="Vendor"), pydantic.Field(alias="Vendor")
    ] = None
    bill_data: typing_extensions.Annotated[
        typing.Optional[typing.List[BillPayOutData]],
        FieldMetadata(alias="BillData"),
        pydantic.Field(alias="BillData", description="Bills associated with the payout subscription."),
    ] = None
    external_paypoint_id: typing_extensions.Annotated[
        typing.Optional[ExternalPaypointId],
        FieldMetadata(alias="ExternalPaypointID"),
        pydantic.Field(alias="ExternalPaypointID"),
    ] = None
    method: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="Method"),
        pydantic.Field(alias="Method", description="The payout subscription's payment method."),
    ] = None
    paypoint_id: typing_extensions.Annotated[
        typing.Optional[PaypointId], FieldMetadata(alias="PaypointId"), pydantic.Field(alias="PaypointId")
    ] = None
    total_amount: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="TotalAmount"),
        pydantic.Field(alias="TotalAmount", description="The payout subscription amount, including any fees."),
    ] = None
    net_amount: typing_extensions.Annotated[
        typing.Optional[Netamountnullable],
        FieldMetadata(alias="NetAmount"),
        pydantic.Field(alias="NetAmount", description="The payout subscription amount, minus any fees."),
    ] = None
    fee_amount: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="FeeAmount"),
        pydantic.Field(alias="FeeAmount", description="Fee applied to the payout subscription."),
    ] = None
    payment_data: typing_extensions.Annotated[
        typing.Optional[QueryPaymentData], FieldMetadata(alias="PaymentData"), pydantic.Field(alias="PaymentData")
    ] = None
    start_date: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="StartDate"),
        pydantic.Field(alias="StartDate", description="The payout subscription start date."),
    ] = None
    end_date: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="EndDate"),
        pydantic.Field(alias="EndDate", description="The payout subscription's end date."),
    ] = None
    next_date: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="NextDate"),
        pydantic.Field(alias="NextDate", description="The next date the payout subscription will be processed."),
    ] = None
    frequency: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="Frequency"),
        pydantic.Field(alias="Frequency", description="The payout subscription's frequency."),
    ] = None
    total_cycles: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="TotalCycles"),
        pydantic.Field(
            alias="TotalCycles", description="The total number of cycles the payout subscription is set to run."
        ),
    ] = None
    left_cycles: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="LeftCycles"),
        pydantic.Field(alias="LeftCycles", description="The number of cycles the payout subscription has left."),
    ] = None
    last_run: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="LastRun"),
        pydantic.Field(alias="LastRun", description="The last time the payout subscription was processed."),
    ] = None
    entrypage_id: typing_extensions.Annotated[
        typing.Optional[EntrypageId], FieldMetadata(alias="EntrypageId"), pydantic.Field(alias="EntrypageId")
    ] = None
    until_cancelled: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="UntilCancelled"),
        pydantic.Field(
            alias="UntilCancelled",
            description="When `true`, the payout subscription has no explicit end date and runs until canceled.",
        ),
    ] = None
    last_updated: typing_extensions.Annotated[
        typing.Optional[LastModified],
        FieldMetadata(alias="LastUpdated"),
        pydantic.Field(alias="LastUpdated", description="The last date and time the payout subscription was updated."),
    ] = None
    created_at: typing_extensions.Annotated[
        typing.Optional[CreatedAt],
        FieldMetadata(alias="CreatedAt"),
        pydantic.Field(alias="CreatedAt", description="Timestamp of when the payout subscription was created, in UTC."),
    ] = None
    paypoint_legalname: typing_extensions.Annotated[
        typing.Optional[Legalname],
        FieldMetadata(alias="PaypointLegalname"),
        pydantic.Field(alias="PaypointLegalname", description="The paypoint's legal name."),
    ] = None
    paypoint_dbaname: typing_extensions.Annotated[
        typing.Optional[Dbaname],
        FieldMetadata(alias="PaypointDbaname"),
        pydantic.Field(alias="PaypointDbaname", description="The paypoint's DBA name."),
    ] = None
    paypoint_entryname: typing_extensions.Annotated[
        typing.Optional[Entrypointfield],
        FieldMetadata(alias="PaypointEntryname"),
        pydantic.Field(alias="PaypointEntryname", description="The paypoint's entryname."),
    ] = None
    parent_org_name: typing_extensions.Annotated[
        typing.Optional[OrgParentName], FieldMetadata(alias="ParentOrgName"), pydantic.Field(alias="ParentOrgName")
    ] = None
    parent_org_id: typing_extensions.Annotated[
        typing.Optional[OrgParentId], FieldMetadata(alias="ParentOrgId"), pydantic.Field(alias="ParentOrgId")
    ] = None
    source: typing_extensions.Annotated[
        typing.Optional[Source], FieldMetadata(alias="Source"), pydantic.Field(alias="Source")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
