# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .bill_pay_out_data import BillPayOutData
from .created_at import CreatedAt
from .dbaname import Dbaname
from .entrypage_id import EntrypageId
from .entrypointfield import Entrypointfield
from .external_paypoint_id import ExternalPaypointId
from .general_events import GeneralEvents
from .last_modified import LastModified
from .legalname import Legalname
from .netamountnullable import Netamountnullable
from .org_parent_id import OrgParentId
from .org_parent_name import OrgParentName
from .paypoint_id import PaypointId
from .query_payment_data import QueryPaymentData
from .source import Source
from .vendor_query_record import VendorQueryRecord


class PayoutSubscriptionQueryRecord(UniversalBaseModel):
    id_out_subscription: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="idOutSubscription"),
        pydantic.Field(alias="idOutSubscription", description="The payout subscription's ID."),
    ] = None
    """
    The payout subscription's ID.
    """

    status: typing.Optional[int] = pydantic.Field(default=None)
    """
    The payout subscription's status.
    - 0: Paused
    - 1: Active
    """

    events: typing.Optional[typing.List[GeneralEvents]] = pydantic.Field(default=None)
    """
    Events associated with the payout subscription.
    """

    vendor: typing.Optional[VendorQueryRecord] = None
    bill_data: typing_extensions.Annotated[
        typing.Optional[typing.List[BillPayOutData]],
        FieldMetadata(alias="billData"),
        pydantic.Field(alias="billData", description="Bills associated with the payout subscription."),
    ] = None
    """
    Bills associated with the payout subscription.
    """

    external_paypoint_id: typing_extensions.Annotated[
        typing.Optional[ExternalPaypointId],
        FieldMetadata(alias="externalPaypointID"),
        pydantic.Field(alias="externalPaypointID"),
    ] = None
    method: typing.Optional[str] = pydantic.Field(default=None)
    """
    The payout subscription's payment method.
    """

    paypoint_id: typing_extensions.Annotated[
        typing.Optional[PaypointId], FieldMetadata(alias="paypointId"), pydantic.Field(alias="paypointId")
    ] = None
    total_amount: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="totalAmount"),
        pydantic.Field(alias="totalAmount", description="The payout subscription amount, including any fees."),
    ] = None
    """
    The payout subscription amount, including any fees.
    """

    net_amount: typing_extensions.Annotated[
        typing.Optional[Netamountnullable],
        FieldMetadata(alias="netAmount"),
        pydantic.Field(alias="netAmount", description="The payout subscription amount, minus any fees."),
    ] = None
    """
    The payout subscription amount, minus any fees.
    """

    fee_amount: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="feeAmount"),
        pydantic.Field(alias="feeAmount", description="Fee applied to the payout subscription."),
    ] = None
    """
    Fee applied to the payout subscription.
    """

    payment_data: typing_extensions.Annotated[
        typing.Optional[QueryPaymentData], FieldMetadata(alias="paymentData"), pydantic.Field(alias="paymentData")
    ] = None
    start_date: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="startDate"),
        pydantic.Field(alias="startDate", description="The payout subscription start date."),
    ] = None
    """
    The payout subscription start date.
    """

    end_date: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="endDate"),
        pydantic.Field(alias="endDate", description="The payout subscription's end date."),
    ] = None
    """
    The payout subscription's end date.
    """

    next_date: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="nextDate"),
        pydantic.Field(alias="nextDate", description="The next date the payout subscription will be processed."),
    ] = None
    """
    The next date the payout subscription will be processed.
    """

    frequency: typing.Optional[str] = pydantic.Field(default=None)
    """
    The payout subscription's frequency.
    """

    total_cycles: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="totalCycles"),
        pydantic.Field(
            alias="totalCycles", description="The total number of cycles the payout subscription is set to run."
        ),
    ] = None
    """
    The total number of cycles the payout subscription is set to run.
    """

    left_cycles: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="leftCycles"),
        pydantic.Field(alias="leftCycles", description="The number of cycles the payout subscription has left."),
    ] = None
    """
    The number of cycles the payout subscription has left.
    """

    last_run: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="lastRun"),
        pydantic.Field(alias="lastRun", description="The last time the payout subscription was processed."),
    ] = None
    """
    The last time the payout subscription was processed.
    """

    entrypage_id: typing_extensions.Annotated[
        typing.Optional[EntrypageId], FieldMetadata(alias="entrypageId"), pydantic.Field(alias="entrypageId")
    ] = None
    until_cancelled: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="untilCancelled"),
        pydantic.Field(
            alias="untilCancelled",
            description="When `true`, the payout subscription has no explicit end date and runs until canceled.",
        ),
    ] = None
    """
    When `true`, the payout subscription has no explicit end date and runs until canceled.
    """

    last_updated: typing_extensions.Annotated[
        typing.Optional[LastModified],
        FieldMetadata(alias="lastUpdated"),
        pydantic.Field(alias="lastUpdated", description="The last date and time the payout subscription was updated."),
    ] = None
    """
    The last date and time the payout subscription was updated.
    """

    created_at: typing_extensions.Annotated[
        typing.Optional[CreatedAt],
        FieldMetadata(alias="createdAt"),
        pydantic.Field(alias="createdAt", description="Timestamp of when the payout subscription was created, in UTC."),
    ] = None
    """
    Timestamp of when the payout subscription was created, in UTC.
    """

    paypoint_legalname: typing_extensions.Annotated[
        typing.Optional[Legalname],
        FieldMetadata(alias="paypointLegalname"),
        pydantic.Field(alias="paypointLegalname", description="The paypoint's legal name."),
    ] = None
    """
    The paypoint's legal name.
    """

    paypoint_dbaname: typing_extensions.Annotated[
        typing.Optional[Dbaname],
        FieldMetadata(alias="paypointDbaname"),
        pydantic.Field(alias="paypointDbaname", description="The paypoint's DBA name."),
    ] = None
    """
    The paypoint's DBA name.
    """

    paypoint_entryname: typing_extensions.Annotated[
        typing.Optional[Entrypointfield],
        FieldMetadata(alias="paypointEntryname"),
        pydantic.Field(alias="paypointEntryname", description="The paypoint's entryname."),
    ] = None
    """
    The paypoint's entryname.
    """

    parent_org_name: typing_extensions.Annotated[
        typing.Optional[OrgParentName], FieldMetadata(alias="parentOrgName"), pydantic.Field(alias="parentOrgName")
    ] = None
    parent_org_id: typing_extensions.Annotated[
        typing.Optional[OrgParentId], FieldMetadata(alias="parentOrgId"), pydantic.Field(alias="parentOrgId")
    ] = None
    source: typing.Optional[Source] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
