# This file was auto-generated by Fern from our API Definition.

PayoutProgram = str
"""
The payout program associated with the transaction. Values are `Managed`
(managed payables) or `ODP` (on-demand payables).
"""
