# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class PaypointRef(UniversalBaseModel):
    """
    A reference to the paypoint the case applies to.
    """

    id: int = pydantic.Field()
    """
    The paypoint's numeric identifier.
    """

    name: str = pydantic.Field()
    """
    The paypoint's DBA name.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
