# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .query_transfer_summary import QueryTransferSummary
from .transaction_query_records import TransactionQueryRecords


class QueryTransferResponse(UniversalBaseModel):
    summary: typing_extensions.Annotated[typing.Optional[QueryTransferSummary], FieldMetadata(alias="Summary")] = (
        pydantic.Field(default=None)
    )
    """
    Summary information about the transfers.
    """

    records: typing_extensions.Annotated[
        typing.Optional[typing.List[TransactionQueryRecords]], FieldMetadata(alias="Records")
    ] = pydantic.Field(default=None)
    """
    List of transfer transaction records.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
