# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .vendor_check_number import VendorCheckNumber


class RequestOutAuthorizePaymentDetails(UniversalBaseModel):
    """
    Object containing payment details.
    """

    check_number: typing_extensions.Annotated[
        typing.Optional[VendorCheckNumber], FieldMetadata(alias="checkNumber"), pydantic.Field(alias="checkNumber")
    ] = None
    currency: typing.Optional[str] = pydantic.Field(default=None)
    """
    Currency code ISO-4217. If no code is provided, then the currency in the paypoint setting is used. Default is **USD**.
    """

    service_fee: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="serviceFee"),
        pydantic.Field(
            alias="serviceFee",
            description="Service fee to deduct from the total amount. This amount must be a number, percentages aren't accepted. If you're using a percentage-based fee schedule, you must calculate the value manually.\n\nPayabli honors this field only when the paypoint's ACH payout pricing allows fee overrides. Otherwise, Payabli ignores this field and charges the fee configured in the paypoint's pricing. Contact Payabli to check or change this setting.\n\nWhen fee overrides are allowed:\n\n- `0` overrides the configured fee, and no fee is charged.\n- A positive value replaces the configured fee. Payabli caps the fee at `totalAmount`.\n- A negative value results in no fee.\n- If you omit this field, Payabli charges the configured fee.\n\nThe fee is deducted from the payout, so the vendor receives `totalAmount` minus the fee.",
        ),
    ] = None
    """
    Service fee to deduct from the total amount. This amount must be a number, percentages aren't accepted. If you're using a percentage-based fee schedule, you must calculate the value manually.
    
    Payabli honors this field only when the paypoint's ACH payout pricing allows fee overrides. Otherwise, Payabli ignores this field and charges the fee configured in the paypoint's pricing. Contact Payabli to check or change this setting.
    
    When fee overrides are allowed:
    
    - `0` overrides the configured fee, and no fee is charged.
    - A positive value replaces the configured fee. Payabli caps the fee at `totalAmount`.
    - A negative value results in no fee.
    - If you omit this field, Payabli charges the configured fee.
    
    The fee is deducted from the payout, so the vendor receives `totalAmount` minus the fee.
    """

    total_amount: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="totalAmount"),
        pydantic.Field(
            alias="totalAmount",
            description="Total amount to be charged. If a service fee is included, then this amount should include the service fee. If you're using managed payables (`paymentMethod.method` of `managed`), you can partially pay a single bill by setting this below the bill's outstanding balance. See [Partially pay a bill](/guides/pay-out-developer-bills-manage#partially-pay-a-bill).",
        ),
    ] = None
    """
    Total amount to be charged. If a service fee is included, then this amount should include the service fee. If you're using managed payables (`paymentMethod.method` of `managed`), you can partially pay a single bill by setting this below the bill's outstanding balance. See [Partially pay a bill](/guides/pay-out-developer-bills-manage#partially-pay-a-bill).
    """

    unbundled: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Indicates whether the payout should be bundled into a single transaction or processed separately. If set to `true`, each bill will be processed as a separate payout. If `false` or not provided, then multiple bills will be paid with a single payout.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
