# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class RoomMessageView(UniversalBaseModel):
    """
    A note on a case.
    """

    id: int = pydantic.Field()
    """
    The message's identifier.
    """

    user_id: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="userId"),
        pydantic.Field(alias="userId", description="The numeric id of the user who posted the note."),
    ]
    """
    The numeric id of the user who posted the note.
    """

    content: str = pydantic.Field()
    """
    The note text.
    """

    created_at: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="createdAt"),
        pydantic.Field(alias="createdAt", description="When the note was posted."),
    ]
    """
    When the note was posted.
    """

    updated_at: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="updatedAt"),
        pydantic.Field(alias="updatedAt", description="When the note was last edited. Null when never edited."),
    ] = None
    """
    When the note was last edited. Null when never edited.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
