# This file was auto-generated by Fern from our API Definition.

ServiceValue = int
"""
Service the event applies to, serialized as an integer: `1` Card,
`2` VCard, `3` Ach, `4` Cloud, `5` Cash, `6` Check, `7` Managed, `8` SDAch,
`9` Wallet, `10` Wire, `11` Rtp, `12` Device.
"""
