# This file was auto-generated by Fern from our API Definition.

SignerCountry = str
"""
The signer's country in ISO-3166-1 alpha 2 format. See
[ISO 3166-1](https://en.wikipedia.org/wiki/ISO_3166-1) for more.
"""
