# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .case_state import CaseState
from .user_ref import UserRef


class StateTransitionResponse(UniversalBaseModel):
    """
    A single entry in a case's state history.
    """

    uuid_: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="uuid"),
        pydantic.Field(alias="uuid", description="The transition's unique identifier."),
    ]
    """
    The transition's unique identifier.
    """

    case_uuid: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="caseUuid"),
        pydantic.Field(alias="caseUuid", description="The case this transition belongs to."),
    ]
    """
    The case this transition belongs to.
    """

    from_state: typing_extensions.Annotated[
        CaseState, FieldMetadata(alias="fromState"), pydantic.Field(alias="fromState")
    ]
    to_state: typing_extensions.Annotated[CaseState, FieldMetadata(alias="toState"), pydantic.Field(alias="toState")]
    ip_address: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="ipAddress"),
        pydantic.Field(alias="ipAddress", description="The IP address of the actor. Null for system transitions."),
    ] = None
    """
    The IP address of the actor. Null for system transitions.
    """

    triggered_by: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="triggeredBy"),
        pydantic.Field(
            alias="triggeredBy",
            description="The numeric id of the user who triggered the transition. Null for system transitions.",
        ),
    ] = None
    """
    The numeric id of the user who triggered the transition. Null for system transitions.
    """

    reason: typing.Optional[str] = pydantic.Field(default=None)
    """
    The reason recorded for the transition.
    """

    created_at: typing_extensions.Annotated[
        dt.datetime,
        FieldMetadata(alias="createdAt"),
        pydantic.Field(alias="createdAt", description="When the transition occurred."),
    ]
    """
    When the transition occurred.
    """

    triggered_by_user: typing_extensions.Annotated[
        typing.Optional[UserRef],
        FieldMetadata(alias="triggeredByUser"),
        pydantic.Field(
            alias="triggeredByUser",
            description="The resolved user who triggered the transition. Null for system transitions.",
        ),
    ] = None
    """
    The resolved user who triggered the transition. Null for system transitions.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
