# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class StatisticsVendorQueryRecord(UniversalBaseModel):
    stat_x: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="statX"),
        pydantic.Field(
            alias="statX",
            description="The time bucket for this row, formatted according to the query's `freq` (for example, `2025-11` for a monthly bucket). Each bill falls in the bucket of its most recent update. The counts below break the vendor's bills down by bill state.",
        ),
    ]
    """
    The time bucket for this row, formatted according to the query's `freq` (for example, `2025-11` for a monthly bucket). Each bill falls in the bucket of its most recent update. The counts below break the vendor's bills down by bill state.
    """

    active: int = pydantic.Field()
    """
    Number of the vendor's bills in the active state (created, not yet submitted for approval).
    """

    active_volume: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="activeVolume"),
        pydantic.Field(alias="activeVolume", description="Total value of the vendor's active bills, net of fees."),
    ]
    """
    Total value of the vendor's active bills, net of fees.
    """

    sent_to_approval: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="sentToApproval"),
        pydantic.Field(
            alias="sentToApproval", description="Number of the vendor's bills submitted into an approval workflow."
        ),
    ]
    """
    Number of the vendor's bills submitted into an approval workflow.
    """

    sent_to_approval_volume: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="sentToApprovalVolume"),
        pydantic.Field(
            alias="sentToApprovalVolume", description="Total value of the vendor's bills sent to approval, net of fees."
        ),
    ]
    """
    Total value of the vendor's bills sent to approval, net of fees.
    """

    to_approval: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="toApproval"),
        pydantic.Field(alias="toApproval", description="Number of the vendor's bills awaiting an approver's decision."),
    ]
    """
    Number of the vendor's bills awaiting an approver's decision.
    """

    to_approval_volume: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="toApprovalVolume"),
        pydantic.Field(
            alias="toApprovalVolume", description="Total value of the vendor's bills awaiting approval, net of fees."
        ),
    ]
    """
    Total value of the vendor's bills awaiting approval, net of fees.
    """

    approved: int = pydantic.Field()
    """
    Number of the vendor's bills approved for payment.
    """

    approved_volume: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="approvedVolume"),
        pydantic.Field(alias="approvedVolume", description="Total value of the vendor's approved bills, net of fees."),
    ]
    """
    Total value of the vendor's approved bills, net of fees.
    """

    disapproved: int = pydantic.Field()
    """
    Number of the vendor's bills rejected during approval.
    """

    disapproved_volume: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="disapprovedVolume"),
        pydantic.Field(
            alias="disapprovedVolume", description="Total value of the vendor's disapproved bills, net of fees."
        ),
    ]
    """
    Total value of the vendor's disapproved bills, net of fees.
    """

    cancelled: int = pydantic.Field()
    """
    Number of the vendor's cancelled bills.
    """

    cancelled_volume: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="cancelledVolume"),
        pydantic.Field(
            alias="cancelledVolume", description="Total value of the vendor's cancelled bills, net of fees."
        ),
    ]
    """
    Total value of the vendor's cancelled bills, net of fees.
    """

    in_transit: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="inTransit"),
        pydantic.Field(alias="inTransit", description="Number of the vendor's bills whose payment is in transit."),
    ]
    """
    Number of the vendor's bills whose payment is in transit.
    """

    in_transit_volume: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="inTransitVolume"),
        pydantic.Field(
            alias="inTransitVolume", description="Total value of the vendor's in-transit bills, net of fees."
        ),
    ]
    """
    Total value of the vendor's in-transit bills, net of fees.
    """

    paid: int = pydantic.Field()
    """
    Number of the vendor's bills marked paid. Paid means the payout has settled, not merely that Payabli issued it.
    """

    paid_volume: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="paidVolume"),
        pydantic.Field(alias="paidVolume", description="Total value of the vendor's paid bills, net of fees."),
    ]
    """
    Total value of the vendor's paid bills, net of fees.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
