# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .is_success import IsSuccess
from .response_text import ResponseText
from .tap_to_pay_activation_challenge_error_response_response_data import (
    TapToPayActivationChallengeErrorResponseResponseData,
)


class TapToPayActivationChallengeErrorResponse(UniversalBaseModel):
    """
    Error response for a Tap to Pay activation challenge request.
    `responseData` carries the same status code as the HTTP response
    and a message describing the refusal.
    """

    is_success: typing_extensions.Annotated[
        IsSuccess, FieldMetadata(alias="isSuccess"), pydantic.Field(alias="isSuccess")
    ]
    response_text: typing_extensions.Annotated[
        ResponseText, FieldMetadata(alias="responseText"), pydantic.Field(alias="responseText")
    ]
    response_data: typing_extensions.Annotated[
        TapToPayActivationChallengeErrorResponseResponseData,
        FieldMetadata(alias="responseData"),
        pydantic.Field(alias="responseData"),
    ]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
