# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class UserRef(UniversalBaseModel):
    """
    A reference to a user, with the display name resolved when available.
    """

    id: int = pydantic.Field()
    """
    The user's numeric identifier.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The user's display name. Null when the name can't be resolved.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
