# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .authcode import Authcode
from .avs_response import AvsResponse
from .avs_response_text import AvsResponseText
from .customer_vault_id import CustomerVaultId
from .cvv_response import CvvResponse
from .cvv_response_text import CvvResponseText
from .emv_auth_response_data import EmvAuthResponseData
from .order_id import OrderId
from .result_code_text import ResultCodeText
from .result_codev_2 import ResultCodev2
from .resulttext import Resulttext


class V2TransactionDetailResponseData(UniversalBaseModel):
    """
    Response data from payment processor
    """

    result_code: typing_extensions.Annotated[
        ResultCodev2, FieldMetadata(alias="resultCode"), pydantic.Field(alias="resultCode")
    ]
    result_code_text: typing_extensions.Annotated[
        ResultCodeText, FieldMetadata(alias="resultCodeText"), pydantic.Field(alias="resultCodeText")
    ]
    response: typing.Optional[str] = None
    responsetext: Resulttext
    authcode: typing.Optional[Authcode] = None
    transactionid: str = pydantic.Field()
    """
    Unique identifier for the transaction assigned by the payment processor.
    """

    avsresponse: typing.Optional[AvsResponse] = None
    avsresponse_text: typing.Optional[AvsResponseText] = None
    cvvresponse: typing.Optional[CvvResponse] = None
    cvvresponse_text: typing.Optional[CvvResponseText] = None
    orderid: typing.Optional[OrderId] = None
    type: typing.Optional[str] = None
    response_code: str = pydantic.Field()
    """
    Processor-specific response code.
    """

    response_code_text: str = pydantic.Field()
    """
    Description of the response code.
    """

    customer_vault_id: typing.Optional[CustomerVaultId] = None
    emv_auth_response_data: typing.Optional[EmvAuthResponseData] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
