# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .page_identifier import PageIdentifier
from .pagesize import Pagesize
from .totalpages import Totalpages
from .totalrecords import Totalrecords


class VCardSummary(UniversalBaseModel):
    total_pages: typing_extensions.Annotated[
        Totalpages, FieldMetadata(alias="totalPages"), pydantic.Field(alias="totalPages")
    ]
    total_records: typing_extensions.Annotated[
        Totalrecords, FieldMetadata(alias="totalRecords"), pydantic.Field(alias="totalRecords")
    ]
    total_amount: typing_extensions.Annotated[
        float,
        FieldMetadata(alias="totalAmount"),
        pydantic.Field(alias="totalAmount", description="Total amount for the records."),
    ]
    total_net_amount: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="totalNetAmount"),
        pydantic.Field(alias="totalNetAmount", description="Total net amount for the records."),
    ] = None
    totalactive: int = pydantic.Field()
    """
    Total number of active vCards.
    """

    totalamountactive: float = pydantic.Field()
    """
    Total amount of active vCards.
    """

    totalbalanceactive: float = pydantic.Field()
    """
    Total balance of active vCards.
    """

    pageidentifier: typing.Optional[PageIdentifier] = None
    page_size: typing_extensions.Annotated[
        typing.Optional[Pagesize], FieldMetadata(alias="pageSize"), pydantic.Field(alias="pageSize")
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
