# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata


class VendorCallStatusScheduled(UniversalBaseModel):
    """
    Details of a queued or in-progress outreach call.
    """

    scheduled_for: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="scheduledFor"),
        pydantic.Field(alias="scheduledFor", description="ISO-8601 timestamp of the next scheduled call attempt."),
    ] = None
    attempts_remaining: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="attemptsRemaining"),
        pydantic.Field(
            alias="attemptsRemaining", description="Number of call attempts left before retries are exhausted."
        ),
    ] = None
    max_attempts: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="maxAttempts"),
        pydantic.Field(
            alias="maxAttempts", description="Maximum number of call attempts configured for this schedule."
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
