# This file was auto-generated by Fern from our API Definition.

import datetime as dt
import typing

from .. import core
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.attachment_response import AttachmentResponse
from ..types.available_transitions_response import AvailableTransitionsResponse
from ..types.bank_account_services import BankAccountServices
from ..types.bank_review_decision_reason import BankReviewDecisionReason
from ..types.case_list_response import CaseListResponse
from ..types.case_management_bank_account_function import CaseManagementBankAccountFunction
from ..types.case_response import CaseResponse
from ..types.case_trigger import CaseTrigger
from ..types.message_page import MessagePage
from ..types.posted_message import PostedMessage
from ..types.pre_creation_validation_result import PreCreationValidationResult
from .raw_client import AsyncRawCaseManagementClient, RawCaseManagementClient

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class CaseManagementClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawCaseManagementClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawCaseManagementClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawCaseManagementClient
        """
        return self._raw_client

    def validate_bank_account_change(
        self,
        paypoint_id: int,
        *,
        routing_number: str,
        account_number: str,
        account_type: str,
        bank_account_holder_type: str,
        bank_account_function: CaseManagementBankAccountFunction,
        services: BankAccountServices,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PreCreationValidationResult:
        """
        Validates a bank account change for a paypoint without creating a case.
        Runs the same checks the create endpoint runs, and returns blocking
        conditions and warnings. Blocking conditions prevent creation; warnings
        don't.

        Available to both Platform and Enterprise Partners.

        Parameters
        ----------
        paypoint_id : int
            The paypoint's numeric identifier.

        routing_number : str
            The 9-digit bank routing number.

        account_number : str
            The bank account number (4 to 17 digits).

        account_type : str
            The account type. Must be `checking` or `savings`.

        bank_account_holder_type : str
            The account holder type. Must be `personal` or `business`.

        bank_account_function : CaseManagementBankAccountFunction

        services : BankAccountServices

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PreCreationValidationResult
            Validation result

        Examples
        --------
        from payabli import BankAccountServices, payabli

        client = payabli(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.case_management.validate_bank_account_change(
            paypoint_id=3040,
            routing_number="123456789",
            account_number="987654321",
            account_type="checking",
            bank_account_holder_type="business",
            bank_account_function="Deposits",
            services=BankAccountServices(
                money_in=["Ach"],
                money_out=["Ach"],
            ),
        )
        """
        _response = self._raw_client.validate_bank_account_change(
            paypoint_id,
            routing_number=routing_number,
            account_number=account_number,
            account_type=account_type,
            bank_account_holder_type=bank_account_holder_type,
            bank_account_function=bank_account_function,
            services=services,
            request_options=request_options,
        )
        return _response.data

    def create_bank_account_change(
        self,
        paypoint_id: int,
        *,
        nickname: str,
        bank_name: str,
        routing_number: str,
        account_number: str,
        account_type: str,
        bank_account_holder_type: str,
        bank_account_function: CaseManagementBankAccountFunction,
        services: BankAccountServices,
        default: bool,
        schedule_for: typing.Optional[dt.datetime] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CaseResponse:
        """
        Creates a bank-account-change case for a paypoint. The account and
        routing numbers are validated and tokenized before the case is saved —
        the raw numbers are never stored or returned. The account holder name is
        taken from the paypoint's legal name. On success the case is created in
        `Submitted` and asynchronous verification starts.

        Available to both Platform and Enterprise Partners.

        Parameters
        ----------
        paypoint_id : int
            The paypoint's numeric identifier.

        nickname : str
            A label for the account.

        bank_name : str
            The name of the bank.

        routing_number : str
            The 9-digit bank routing number.

        account_number : str
            The bank account number (4 to 17 digits).

        account_type : str
            The account type. Must be `checking` or `savings`.

        bank_account_holder_type : str
            The account holder type. Must be `personal` or `business`.

        bank_account_function : CaseManagementBankAccountFunction

        services : BankAccountServices

        default : bool
            Whether this is the default account for the selected services.

        schedule_for : typing.Optional[dt.datetime]
            When to run the change, as a UTC timestamp (trailing `Z`). Must be at
            least 1 hour and at most 30 days in the future. Omit to run as soon as
            the case is approved.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CaseResponse
            The created case

        Examples
        --------
        from payabli import BankAccountServices, payabli

        client = payabli(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.case_management.create_bank_account_change(
            paypoint_id=3040,
            nickname="Main Settlement Account",
            bank_name="First National Bank",
            routing_number="123456789",
            account_number="987654321",
            account_type="checking",
            bank_account_holder_type="business",
            bank_account_function="Deposits",
            services=BankAccountServices(
                money_in=["Ach"],
                money_out=["Ach"],
            ),
            default=True,
        )
        """
        _response = self._raw_client.create_bank_account_change(
            paypoint_id,
            nickname=nickname,
            bank_name=bank_name,
            routing_number=routing_number,
            account_number=account_number,
            account_type=account_type,
            bank_account_holder_type=bank_account_holder_type,
            bank_account_function=bank_account_function,
            services=services,
            default=default,
            schedule_for=schedule_for,
            request_options=request_options,
        )
        return _response.data

    def get_case(self, uuid_: str, *, request_options: typing.Optional[RequestOptions] = None) -> CaseResponse:
        """
        Returns a case by its UUID, including its current state, parameters,
        state history, verification metadata, and attachments.

        Available to both Platform and Enterprise Partners.

        Parameters
        ----------
        uuid_ : str
            The case's UUID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CaseResponse
            The case

        Examples
        --------
        from payabli import payabli

        client = payabli(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.case_management.get_case(
            uuid_="9c2b7e14-3a5f-4d21-b8e0-1f6a4c9d2e70",
        )
        """
        _response = self._raw_client.get_case(uuid_, request_options=request_options)
        return _response.data

    def list_cases(
        self,
        organization_id: int,
        *,
        from_record: typing.Optional[int] = None,
        limit_record: typing.Optional[int] = None,
        sort_by: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CaseListResponse:
        """
        Lists cases for an organization, climbing the platform org hierarchy.
        Supports pagination and sorting through query parameters, and filtering
        through repeatable `parameters[field(op)]=value` query parameters (for
        example `parameters[state(in)]=Assigned|PendingReview`). Filterable
        fields include `state`, `caseType`, `paypointId`, `createdAt`,
        `updatedAt`, `scheduleFor`, and `createdBy`.

        Available to both Platform and Enterprise Partners.

        Parameters
        ----------
        organization_id : int
            The organization's numeric identifier.

        from_record : typing.Optional[int]
            The zero-based index of the first record to return.

        limit_record : typing.Optional[int]
            The maximum number of records to return (1 to 200).

        sort_by : typing.Optional[str]
            Sort expression, such as `desc(createdAt)` or `asc(state)`. Defaults to `desc(createdAt)`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CaseListResponse
            A page of cases

        Examples
        --------
        from payabli import payabli

        client = payabli(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.case_management.list_cases(
            organization_id=123,
            from_record=0,
            limit_record=20,
        )
        """
        _response = self._raw_client.list_cases(
            organization_id,
            from_record=from_record,
            limit_record=limit_record,
            sort_by=sort_by,
            request_options=request_options,
        )
        return _response.data

    def list_messages(
        self,
        case_uuid: str,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MessagePage:
        """
        Lists the notes on a case, ordered oldest to newest. Cursor-paginated.

        Available to both Platform and Enterprise Partners.

        Parameters
        ----------
        case_uuid : str
            The case's UUID.

        limit : typing.Optional[int]
            The maximum number of notes to return (default 50, max 200).

        cursor : typing.Optional[str]
            An opaque cursor for the next page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MessagePage
            A page of notes

        Examples
        --------
        from payabli import payabli

        client = payabli(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.case_management.list_messages(
            case_uuid="9c2b7e14-3a5f-4d21-b8e0-1f6a4c9d2e70",
        )
        """
        _response = self._raw_client.list_messages(
            case_uuid, limit=limit, cursor=cursor, request_options=request_options
        )
        return _response.data

    def post_message(
        self, case_uuid: str, *, content: str, request_options: typing.Optional[RequestOptions] = None
    ) -> PostedMessage:
        """
        Adds a note to a case.

        Available to both Platform and Enterprise Partners.

        This endpoint is in development and not yet available for API use. To
        add a note for now, use Case Management in the
        [Payabli Portal](/guides/pay-ops-portal-bank-account-changes-manage).
        To read existing notes on a case, use
        [List case notes](/developers/api-reference/caseManagement/list-case-notes).

        Parameters
        ----------
        case_uuid : str
            The case's UUID.

        content : str
            The note text (1 to 4000 characters).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostedMessage
            The posted note

        Examples
        --------
        from payabli import payabli

        client = payabli(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.case_management.post_message(
            case_uuid="9c2b7e14-3a5f-4d21-b8e0-1f6a4c9d2e70",
            content="Reviewed supporting documents; account ownership confirmed.",
        )
        """
        _response = self._raw_client.post_message(case_uuid, content=content, request_options=request_options)
        return _response.data

    def list_transitions(
        self, uuid_: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AvailableTransitionsResponse:
        """
        Lists the review actions currently available on a case. The list is
        empty when no user action is available (for example while the case is
        mid-automation).

        Available to both Platform and Enterprise Partners, though only
        Enterprise Partners can fire the returned actions.

        Parameters
        ----------
        uuid_ : str
            The case's UUID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AvailableTransitionsResponse
            The available actions

        Examples
        --------
        from payabli import payabli

        client = payabli(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.case_management.list_transitions(
            uuid_="9c2b7e14-3a5f-4d21-b8e0-1f6a4c9d2e70",
        )
        """
        _response = self._raw_client.list_transitions(uuid_, request_options=request_options)
        return _response.data

    def transition(
        self,
        uuid_: str,
        *,
        trigger: CaseTrigger,
        reason: str,
        decline_reason: typing.Optional[BankReviewDecisionReason] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CaseResponse:
        """
        Fires a review action on a case, such as `Approve`, `Deny`, `Escalate`,
        or `RequestReview`. Assigning a case uses the dedicated assign endpoint,
        not this one. Firing an action that isn't valid for the case's current
        state returns `409`.

        Available to Enterprise Partners only.

        Parameters
        ----------
        uuid_ : str
            The case's UUID.

        trigger : CaseTrigger

        reason : str
            The reason for the action.

        decline_reason : typing.Optional[BankReviewDecisionReason]
            The decline reason. Required when the trigger is `Deny`, and must be omitted otherwise.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CaseResponse
            The updated case

        Examples
        --------
        from payabli import payabli

        client = payabli(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.case_management.transition(
            uuid_="9c2b7e14-3a5f-4d21-b8e0-1f6a4c9d2e70",
            trigger="Approve",
            reason="Account ownership confirmed with the merchant by phone.",
        )
        """
        _response = self._raw_client.transition(
            uuid_, trigger=trigger, reason=reason, decline_reason=decline_reason, request_options=request_options
        )
        return _response.data

    def assign_case(
        self,
        uuid_: str,
        *,
        assignee_id: int,
        reason: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CaseResponse:
        """
        Assigns a case to a reviewer.

        Available to Enterprise Partners only.

        Parameters
        ----------
        uuid_ : str
            The case's UUID.

        assignee_id : int
            The numeric id of the reviewer to assign the case to.

        reason : typing.Optional[str]
            An optional reason for the assignment.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CaseResponse
            The assigned case

        Examples
        --------
        from payabli import payabli

        client = payabli(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.case_management.assign_case(
            uuid_="9c2b7e14-3a5f-4d21-b8e0-1f6a4c9d2e70",
            assignee_id=4238,
            reason="Routing to the risk team for review.",
        )
        """
        _response = self._raw_client.assign_case(
            uuid_, assignee_id=assignee_id, reason=reason, request_options=request_options
        )
        return _response.data

    def list_attachments(
        self, case_uuid: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[AttachmentResponse]:
        """
        Lists the files attached to a case.

        Available to both Platform and Enterprise Partners.

        Parameters
        ----------
        case_uuid : str
            The case's UUID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[AttachmentResponse]
            The attachments

        Examples
        --------
        from payabli import payabli

        client = payabli(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.case_management.list_attachments(
            case_uuid="9c2b7e14-3a5f-4d21-b8e0-1f6a4c9d2e70",
        )
        """
        _response = self._raw_client.list_attachments(case_uuid, request_options=request_options)
        return _response.data

    def upload_attachment(
        self, case_uuid: str, *, file: core.File, request_options: typing.Optional[RequestOptions] = None
    ) -> AttachmentResponse:
        """
        Uploads a file to a case as multipart form data. The maximum size is
        25 MiB, and the content type must be an allowed type such as PDF, PNG,
        JPEG, CSV, XLSX, DOCX, or plain text.

        Available to both Platform and Enterprise Partners.

        Parameters
        ----------
        case_uuid : str
            The case's UUID.

        file : core.File
            See core.File for more documentation

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AttachmentResponse
            The uploaded attachment

        Examples
        --------
        from payabli import payabli

        client = payabli(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.case_management.upload_attachment(
            case_uuid="caseUuid",
        )
        """
        _response = self._raw_client.upload_attachment(case_uuid, file=file, request_options=request_options)
        return _response.data

    def get_attachment(
        self, case_uuid: str, attachment_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.Iterator[bytes]:
        """
        Streams the file content of an attachment.

        Available to both Platform and Enterprise Partners.

        Parameters
        ----------
        case_uuid : str
            The case's UUID.

        attachment_id : str
            The attachment's UUID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        typing.Iterator[bytes]
            The file content

        Examples
        --------
        from payabli import payabli

        client = payabli(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.case_management.get_attachment(
            case_uuid="caseUuid",
            attachment_id="attachmentId",
        )
        """
        with self._raw_client.get_attachment(case_uuid, attachment_id, request_options=request_options) as r:
            yield from r.data

    def delete_attachment(
        self, case_uuid: str, attachment_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Deletes an attachment from a case.

        Available to both Platform and Enterprise Partners.

        Parameters
        ----------
        case_uuid : str
            The case's UUID.

        attachment_id : str
            The attachment's UUID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        from payabli import payabli

        client = payabli(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.case_management.delete_attachment(
            case_uuid="caseUuid",
            attachment_id="attachmentId",
        )
        """
        _response = self._raw_client.delete_attachment(case_uuid, attachment_id, request_options=request_options)
        return _response.data


class AsyncCaseManagementClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawCaseManagementClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawCaseManagementClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawCaseManagementClient
        """
        return self._raw_client

    async def validate_bank_account_change(
        self,
        paypoint_id: int,
        *,
        routing_number: str,
        account_number: str,
        account_type: str,
        bank_account_holder_type: str,
        bank_account_function: CaseManagementBankAccountFunction,
        services: BankAccountServices,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> PreCreationValidationResult:
        """
        Validates a bank account change for a paypoint without creating a case.
        Runs the same checks the create endpoint runs, and returns blocking
        conditions and warnings. Blocking conditions prevent creation; warnings
        don't.

        Available to both Platform and Enterprise Partners.

        Parameters
        ----------
        paypoint_id : int
            The paypoint's numeric identifier.

        routing_number : str
            The 9-digit bank routing number.

        account_number : str
            The bank account number (4 to 17 digits).

        account_type : str
            The account type. Must be `checking` or `savings`.

        bank_account_holder_type : str
            The account holder type. Must be `personal` or `business`.

        bank_account_function : CaseManagementBankAccountFunction

        services : BankAccountServices

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PreCreationValidationResult
            Validation result

        Examples
        --------
        import asyncio

        from payabli import Asyncpayabli, BankAccountServices

        client = Asyncpayabli(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.case_management.validate_bank_account_change(
                paypoint_id=3040,
                routing_number="123456789",
                account_number="987654321",
                account_type="checking",
                bank_account_holder_type="business",
                bank_account_function="Deposits",
                services=BankAccountServices(
                    money_in=["Ach"],
                    money_out=["Ach"],
                ),
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.validate_bank_account_change(
            paypoint_id,
            routing_number=routing_number,
            account_number=account_number,
            account_type=account_type,
            bank_account_holder_type=bank_account_holder_type,
            bank_account_function=bank_account_function,
            services=services,
            request_options=request_options,
        )
        return _response.data

    async def create_bank_account_change(
        self,
        paypoint_id: int,
        *,
        nickname: str,
        bank_name: str,
        routing_number: str,
        account_number: str,
        account_type: str,
        bank_account_holder_type: str,
        bank_account_function: CaseManagementBankAccountFunction,
        services: BankAccountServices,
        default: bool,
        schedule_for: typing.Optional[dt.datetime] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CaseResponse:
        """
        Creates a bank-account-change case for a paypoint. The account and
        routing numbers are validated and tokenized before the case is saved —
        the raw numbers are never stored or returned. The account holder name is
        taken from the paypoint's legal name. On success the case is created in
        `Submitted` and asynchronous verification starts.

        Available to both Platform and Enterprise Partners.

        Parameters
        ----------
        paypoint_id : int
            The paypoint's numeric identifier.

        nickname : str
            A label for the account.

        bank_name : str
            The name of the bank.

        routing_number : str
            The 9-digit bank routing number.

        account_number : str
            The bank account number (4 to 17 digits).

        account_type : str
            The account type. Must be `checking` or `savings`.

        bank_account_holder_type : str
            The account holder type. Must be `personal` or `business`.

        bank_account_function : CaseManagementBankAccountFunction

        services : BankAccountServices

        default : bool
            Whether this is the default account for the selected services.

        schedule_for : typing.Optional[dt.datetime]
            When to run the change, as a UTC timestamp (trailing `Z`). Must be at
            least 1 hour and at most 30 days in the future. Omit to run as soon as
            the case is approved.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CaseResponse
            The created case

        Examples
        --------
        import asyncio

        from payabli import Asyncpayabli, BankAccountServices

        client = Asyncpayabli(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.case_management.create_bank_account_change(
                paypoint_id=3040,
                nickname="Main Settlement Account",
                bank_name="First National Bank",
                routing_number="123456789",
                account_number="987654321",
                account_type="checking",
                bank_account_holder_type="business",
                bank_account_function="Deposits",
                services=BankAccountServices(
                    money_in=["Ach"],
                    money_out=["Ach"],
                ),
                default=True,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_bank_account_change(
            paypoint_id,
            nickname=nickname,
            bank_name=bank_name,
            routing_number=routing_number,
            account_number=account_number,
            account_type=account_type,
            bank_account_holder_type=bank_account_holder_type,
            bank_account_function=bank_account_function,
            services=services,
            default=default,
            schedule_for=schedule_for,
            request_options=request_options,
        )
        return _response.data

    async def get_case(self, uuid_: str, *, request_options: typing.Optional[RequestOptions] = None) -> CaseResponse:
        """
        Returns a case by its UUID, including its current state, parameters,
        state history, verification metadata, and attachments.

        Available to both Platform and Enterprise Partners.

        Parameters
        ----------
        uuid_ : str
            The case's UUID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CaseResponse
            The case

        Examples
        --------
        import asyncio

        from payabli import Asyncpayabli

        client = Asyncpayabli(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.case_management.get_case(
                uuid_="9c2b7e14-3a5f-4d21-b8e0-1f6a4c9d2e70",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_case(uuid_, request_options=request_options)
        return _response.data

    async def list_cases(
        self,
        organization_id: int,
        *,
        from_record: typing.Optional[int] = None,
        limit_record: typing.Optional[int] = None,
        sort_by: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CaseListResponse:
        """
        Lists cases for an organization, climbing the platform org hierarchy.
        Supports pagination and sorting through query parameters, and filtering
        through repeatable `parameters[field(op)]=value` query parameters (for
        example `parameters[state(in)]=Assigned|PendingReview`). Filterable
        fields include `state`, `caseType`, `paypointId`, `createdAt`,
        `updatedAt`, `scheduleFor`, and `createdBy`.

        Available to both Platform and Enterprise Partners.

        Parameters
        ----------
        organization_id : int
            The organization's numeric identifier.

        from_record : typing.Optional[int]
            The zero-based index of the first record to return.

        limit_record : typing.Optional[int]
            The maximum number of records to return (1 to 200).

        sort_by : typing.Optional[str]
            Sort expression, such as `desc(createdAt)` or `asc(state)`. Defaults to `desc(createdAt)`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CaseListResponse
            A page of cases

        Examples
        --------
        import asyncio

        from payabli import Asyncpayabli

        client = Asyncpayabli(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.case_management.list_cases(
                organization_id=123,
                from_record=0,
                limit_record=20,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_cases(
            organization_id,
            from_record=from_record,
            limit_record=limit_record,
            sort_by=sort_by,
            request_options=request_options,
        )
        return _response.data

    async def list_messages(
        self,
        case_uuid: str,
        *,
        limit: typing.Optional[int] = None,
        cursor: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> MessagePage:
        """
        Lists the notes on a case, ordered oldest to newest. Cursor-paginated.

        Available to both Platform and Enterprise Partners.

        Parameters
        ----------
        case_uuid : str
            The case's UUID.

        limit : typing.Optional[int]
            The maximum number of notes to return (default 50, max 200).

        cursor : typing.Optional[str]
            An opaque cursor for the next page.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        MessagePage
            A page of notes

        Examples
        --------
        import asyncio

        from payabli import Asyncpayabli

        client = Asyncpayabli(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.case_management.list_messages(
                case_uuid="9c2b7e14-3a5f-4d21-b8e0-1f6a4c9d2e70",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_messages(
            case_uuid, limit=limit, cursor=cursor, request_options=request_options
        )
        return _response.data

    async def post_message(
        self, case_uuid: str, *, content: str, request_options: typing.Optional[RequestOptions] = None
    ) -> PostedMessage:
        """
        Adds a note to a case.

        Available to both Platform and Enterprise Partners.

        This endpoint is in development and not yet available for API use. To
        add a note for now, use Case Management in the
        [Payabli Portal](/guides/pay-ops-portal-bank-account-changes-manage).
        To read existing notes on a case, use
        [List case notes](/developers/api-reference/caseManagement/list-case-notes).

        Parameters
        ----------
        case_uuid : str
            The case's UUID.

        content : str
            The note text (1 to 4000 characters).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        PostedMessage
            The posted note

        Examples
        --------
        import asyncio

        from payabli import Asyncpayabli

        client = Asyncpayabli(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.case_management.post_message(
                case_uuid="9c2b7e14-3a5f-4d21-b8e0-1f6a4c9d2e70",
                content="Reviewed supporting documents; account ownership confirmed.",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.post_message(case_uuid, content=content, request_options=request_options)
        return _response.data

    async def list_transitions(
        self, uuid_: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AvailableTransitionsResponse:
        """
        Lists the review actions currently available on a case. The list is
        empty when no user action is available (for example while the case is
        mid-automation).

        Available to both Platform and Enterprise Partners, though only
        Enterprise Partners can fire the returned actions.

        Parameters
        ----------
        uuid_ : str
            The case's UUID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AvailableTransitionsResponse
            The available actions

        Examples
        --------
        import asyncio

        from payabli import Asyncpayabli

        client = Asyncpayabli(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.case_management.list_transitions(
                uuid_="9c2b7e14-3a5f-4d21-b8e0-1f6a4c9d2e70",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_transitions(uuid_, request_options=request_options)
        return _response.data

    async def transition(
        self,
        uuid_: str,
        *,
        trigger: CaseTrigger,
        reason: str,
        decline_reason: typing.Optional[BankReviewDecisionReason] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CaseResponse:
        """
        Fires a review action on a case, such as `Approve`, `Deny`, `Escalate`,
        or `RequestReview`. Assigning a case uses the dedicated assign endpoint,
        not this one. Firing an action that isn't valid for the case's current
        state returns `409`.

        Available to Enterprise Partners only.

        Parameters
        ----------
        uuid_ : str
            The case's UUID.

        trigger : CaseTrigger

        reason : str
            The reason for the action.

        decline_reason : typing.Optional[BankReviewDecisionReason]
            The decline reason. Required when the trigger is `Deny`, and must be omitted otherwise.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CaseResponse
            The updated case

        Examples
        --------
        import asyncio

        from payabli import Asyncpayabli

        client = Asyncpayabli(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.case_management.transition(
                uuid_="9c2b7e14-3a5f-4d21-b8e0-1f6a4c9d2e70",
                trigger="Approve",
                reason="Account ownership confirmed with the merchant by phone.",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.transition(
            uuid_, trigger=trigger, reason=reason, decline_reason=decline_reason, request_options=request_options
        )
        return _response.data

    async def assign_case(
        self,
        uuid_: str,
        *,
        assignee_id: int,
        reason: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CaseResponse:
        """
        Assigns a case to a reviewer.

        Available to Enterprise Partners only.

        Parameters
        ----------
        uuid_ : str
            The case's UUID.

        assignee_id : int
            The numeric id of the reviewer to assign the case to.

        reason : typing.Optional[str]
            An optional reason for the assignment.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CaseResponse
            The assigned case

        Examples
        --------
        import asyncio

        from payabli import Asyncpayabli

        client = Asyncpayabli(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.case_management.assign_case(
                uuid_="9c2b7e14-3a5f-4d21-b8e0-1f6a4c9d2e70",
                assignee_id=4238,
                reason="Routing to the risk team for review.",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.assign_case(
            uuid_, assignee_id=assignee_id, reason=reason, request_options=request_options
        )
        return _response.data

    async def list_attachments(
        self, case_uuid: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.List[AttachmentResponse]:
        """
        Lists the files attached to a case.

        Available to both Platform and Enterprise Partners.

        Parameters
        ----------
        case_uuid : str
            The case's UUID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        typing.List[AttachmentResponse]
            The attachments

        Examples
        --------
        import asyncio

        from payabli import Asyncpayabli

        client = Asyncpayabli(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.case_management.list_attachments(
                case_uuid="9c2b7e14-3a5f-4d21-b8e0-1f6a4c9d2e70",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_attachments(case_uuid, request_options=request_options)
        return _response.data

    async def upload_attachment(
        self, case_uuid: str, *, file: core.File, request_options: typing.Optional[RequestOptions] = None
    ) -> AttachmentResponse:
        """
        Uploads a file to a case as multipart form data. The maximum size is
        25 MiB, and the content type must be an allowed type such as PDF, PNG,
        JPEG, CSV, XLSX, DOCX, or plain text.

        Available to both Platform and Enterprise Partners.

        Parameters
        ----------
        case_uuid : str
            The case's UUID.

        file : core.File
            See core.File for more documentation

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AttachmentResponse
            The uploaded attachment

        Examples
        --------
        import asyncio

        from payabli import Asyncpayabli

        client = Asyncpayabli(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.case_management.upload_attachment(
                case_uuid="caseUuid",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.upload_attachment(case_uuid, file=file, request_options=request_options)
        return _response.data

    async def get_attachment(
        self, case_uuid: str, attachment_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> typing.AsyncIterator[bytes]:
        """
        Streams the file content of an attachment.

        Available to both Platform and Enterprise Partners.

        Parameters
        ----------
        case_uuid : str
            The case's UUID.

        attachment_id : str
            The attachment's UUID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration. You can pass in configuration such as `chunk_size`, and more to customize the request and response.

        Returns
        -------
        typing.AsyncIterator[bytes]
            The file content

        Examples
        --------
        import asyncio

        from payabli import Asyncpayabli

        client = Asyncpayabli(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.case_management.get_attachment(
                case_uuid="caseUuid",
                attachment_id="attachmentId",
            )


        asyncio.run(main())
        """
        async with self._raw_client.get_attachment(case_uuid, attachment_id, request_options=request_options) as r:
            async for _chunk in r.data:
                yield _chunk

    async def delete_attachment(
        self, case_uuid: str, attachment_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> None:
        """
        Deletes an attachment from a case.

        Available to both Platform and Enterprise Partners.

        Parameters
        ----------
        case_uuid : str
            The case's UUID.

        attachment_id : str
            The attachment's UUID.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        None

        Examples
        --------
        import asyncio

        from payabli import Asyncpayabli

        client = Asyncpayabli(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.case_management.delete_attachment(
                case_uuid="caseUuid",
                attachment_id="attachmentId",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.delete_attachment(case_uuid, attachment_id, request_options=request_options)
        return _response.data
