# This file was auto-generated by Fern from our API Definition.

import typing
from json.decoder import JSONDecodeError

from ..core.api_error import ApiError
from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.http_response import AsyncHttpResponse, HttpResponse
from ..core.jsonable_encoder import encode_path_param
from ..core.parse_error import ParsingError
from ..core.pydantic_utilities import parse_obj_as
from ..core.request_options import RequestOptions
from ..errors.internal_server_error import InternalServerError
from ..errors.unauthorized_error import UnauthorizedError
from ..types.device_challenge_response import DeviceChallengeResponse
from ..types.payabli_error_body import PayabliErrorBody
from pydantic import ValidationError


class RawDeviceClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._client_wrapper = client_wrapper

    def challenge(
        self, entry: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> HttpResponse[DeviceChallengeResponse]:
        """
        Generates a one-time, 6-digit verification code for activating a
        semi-integrated card-present device in a paypoint. After calling this endpoint, an operator enters the returned code
        on the device's terminal, along with a device name, to register the
        device to the paypoint resolved from `{entry}`.

        A code expires 5 minutes after it's issued. A paypoint can have several
        codes active at once — for example, when activating a batch of devices —
        and a code binds to whichever device enters it first.

        Authenticate with an OAuth2 Bearer token that has the `device_registry` scope.

        Parameters
        ----------
        entry : str
            The paypoint's entrypoint identifier. [Learn more](/developers/api-reference/api-overview#entrypoint-vs-entry)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        HttpResponse[DeviceChallengeResponse]
            Success
        """
        _endpoint_auth_headers = self._client_wrapper.get_auth_headers_for_endpoint(security=[{"BearerAuth": []}])
        _response = self._client_wrapper.httpx_client.request(
            f"Device/challenge/{encode_path_param(entry)}",
            method="POST",
            headers={
                **_endpoint_auth_headers,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DeviceChallengeResponse,
                    parse_obj_as(
                        type_=DeviceChallengeResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return HttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        PayabliErrorBody,
                        parse_obj_as(
                            type_=PayabliErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)


class AsyncRawDeviceClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._client_wrapper = client_wrapper

    async def challenge(
        self, entry: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> AsyncHttpResponse[DeviceChallengeResponse]:
        """
        Generates a one-time, 6-digit verification code for activating a
        semi-integrated card-present device in a paypoint. After calling this endpoint, an operator enters the returned code
        on the device's terminal, along with a device name, to register the
        device to the paypoint resolved from `{entry}`.

        A code expires 5 minutes after it's issued. A paypoint can have several
        codes active at once — for example, when activating a batch of devices —
        and a code binds to whichever device enters it first.

        Authenticate with an OAuth2 Bearer token that has the `device_registry` scope.

        Parameters
        ----------
        entry : str
            The paypoint's entrypoint identifier. [Learn more](/developers/api-reference/api-overview#entrypoint-vs-entry)

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        AsyncHttpResponse[DeviceChallengeResponse]
            Success
        """
        _endpoint_auth_headers = await self._client_wrapper.async_get_auth_headers_for_endpoint(
            security=[{"BearerAuth": []}]
        )
        _response = await self._client_wrapper.httpx_client.request(
            f"Device/challenge/{encode_path_param(entry)}",
            method="POST",
            headers={
                **_endpoint_auth_headers,
            },
            request_options=request_options,
        )
        try:
            if 200 <= _response.status_code < 300:
                _data = typing.cast(
                    DeviceChallengeResponse,
                    parse_obj_as(
                        type_=DeviceChallengeResponse,  # type: ignore
                        object_=_response.json(),
                    ),
                )
                return AsyncHttpResponse(response=_response, data=_data)
            if _response.status_code == 401:
                raise UnauthorizedError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        PayabliErrorBody,
                        parse_obj_as(
                            type_=PayabliErrorBody,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            if _response.status_code == 500:
                raise InternalServerError(
                    headers=dict(_response.headers),
                    body=typing.cast(
                        typing.Any,
                        parse_obj_as(
                            type_=typing.Any,  # type: ignore
                            object_=_response.json(),
                        ),
                    ),
                )
            _response_json = _response.json()
        except JSONDecodeError:
            raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response.text)
        except ValidationError as e:
            raise ParsingError(
                status_code=_response.status_code, headers=dict(_response.headers), body=_response.json(), cause=e
            )
        raise ApiError(status_code=_response.status_code, headers=dict(_response.headers), body=_response_json)
