# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class DeviceQueryRecord(UniversalBaseModel):
    device_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="deviceId"),
        pydantic.Field(alias="deviceId", description="Unique identifier for the cloud device."),
    ] = None
    id_cloud: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="idCloud"),
        pydantic.Field(alias="idCloud", description="Internal cloud device record ID."),
    ] = None
    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    Description of the device.
    """

    serial_number: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="serialNumber"),
        pydantic.Field(alias="serialNumber", description="Serial number of the device."),
    ] = None
    friendly_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="friendlyName"),
        pydantic.Field(alias="friendlyName", description="Human-readable name for the device."),
    ] = None
    make: typing.Optional[str] = pydantic.Field(default=None)
    """
    Manufacturer of the device.
    """

    model: typing.Optional[str] = pydantic.Field(default=None)
    """
    Model name of the device.
    """

    device_type: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="deviceType"),
        pydantic.Field(alias="deviceType", description="Type of device."),
    ] = None
    device_status: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="deviceStatus"),
        pydantic.Field(alias="deviceStatus", description="Current status of the device."),
    ] = None
    device_os: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="deviceOs"),
        pydantic.Field(alias="deviceOs", description="Operating system of the device."),
    ] = None
    mac_address: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="macAddress"),
        pydantic.Field(alias="macAddress", description="MAC address of the device."),
    ] = None
    last_health_check: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="lastHealthCheck"),
        pydantic.Field(alias="lastHealthCheck", description="Timestamp of the last health check from the device."),
    ] = None
    registration_code: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="registrationCode"),
        pydantic.Field(alias="registrationCode", description="Registration code used to activate the device."),
    ] = None
    activation_attempts: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="activationAttempts"),
        pydantic.Field(alias="activationAttempts", description="Number of activation attempts for the device."),
    ] = None
    activation_code_expiry: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="activationCodeExpiry"),
        pydantic.Field(
            alias="activationCodeExpiry", description="Expiration timestamp for the device activation code."
        ),
    ] = None
    created_at: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="createdAt"),
        pydantic.Field(alias="createdAt", description="Timestamp when the device record was created."),
    ] = None
    updated_at: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="updatedAt"),
        pydantic.Field(alias="updatedAt", description="Timestamp when the device record was last updated."),
    ] = None
    paypoint_id: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="paypointId"),
        pydantic.Field(alias="paypointId", description="Numeric identifier for the paypoint."),
    ] = None
    paypoint_dba: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="paypointDba"),
        pydantic.Field(alias="paypointDba", description="DBA name for the paypoint."),
    ] = None
    paypoint_legal: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="paypointLegal"),
        pydantic.Field(alias="paypointLegal", description="Legal name for the paypoint."),
    ] = None
    paypoint_entry: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="paypointEntry"),
        pydantic.Field(alias="paypointEntry", description="Entry identifier for the paypoint."),
    ] = None
    external_paypoint_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="externalPaypointId"),
        pydantic.Field(alias="externalPaypointId", description="External identifier for the paypoint."),
    ] = None
    parent_org_id: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="parentOrgId"),
        pydantic.Field(alias="parentOrgId", description="Numeric identifier for the parent organization."),
    ] = None
    parent_org_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="parentOrgName"),
        pydantic.Field(alias="parentOrgName", description="Name of the parent organization."),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
