# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class TransferOutDetailVendorBillingData(UniversalBaseModel):
    """
    Billing data for a vendor.
    """

    id: typing.Optional[int] = pydantic.Field(default=None)
    """
    Unique identifier for the billing data.
    """

    account_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="accountId")] = pydantic.Field(
        default=None
    )
    """
    The account ID.
    """

    nickname: typing.Optional[str] = pydantic.Field(default=None)
    """
    A nickname for the account.
    """

    bank_name: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="bankName")] = pydantic.Field(
        default=None
    )
    """
    The name of the bank.
    """

    routing_account: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="routingAccount")] = (
        pydantic.Field(default=None)
    )
    """
    The routing number.
    """

    account_number: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="accountNumber")] = (
        pydantic.Field(default=None)
    )
    """
    The account number.
    """

    type_account: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="typeAccount")] = (
        pydantic.Field(default=None)
    )
    """
    The type of account.
    """

    bank_account_holder_name: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="bankAccountHolderName")
    ] = pydantic.Field(default=None)
    """
    The name of the account holder.
    """

    bank_account_holder_type: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="bankAccountHolderType")
    ] = pydantic.Field(default=None)
    """
    The type of account holder.
    """

    bank_account_function: typing_extensions.Annotated[
        typing.Optional[int], FieldMetadata(alias="bankAccountFunction")
    ] = pydantic.Field(default=None)
    """
    The function of the bank account.
    """

    verified: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether the account is verified.
    """

    status: typing.Optional[int] = pydantic.Field(default=None)
    """
    The status of the billing data.
    """

    services: typing.Optional[typing.List[typing.Any]] = pydantic.Field(default=None)
    """
    Services associated with the billing data.
    """

    default: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether this is the default billing data.
    """

    country: typing.Optional[str] = pydantic.Field(default=None)
    """
    The country of the bank account.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
