# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata
from ...types.dbaname import Dbaname
from ...types.external_paypoint_id import ExternalPaypointId
from ...types.legalname import Legalname
from ...types.mcc import Mcc
from ...types.org_parent_name import OrgParentName


class VCardTransactionRecord(UniversalBaseModel):
    """
    A virtual card transaction record returned by the query.

    Examples
    --------
    from payabli.query_types import VCardTransactionRecord

    VCardTransactionRecord(
        identifier="7HQ2P9B4XD",
        card_token="5RJ8MN2KC4",
        last_four="1234",
        expiration_date="06-30-2029",
        mcc="5943",
        payout_id=84210,
        customer_id=1542,
        vendor_id=9821,
        misc_data_1="Invoice #12345",
        misc_data_2="Project: Office Supplies",
        current_uses=1,
        amount=500.0,
        balance=425.5,
        paypoint_id=236,
        paypoint_legal="Global Factory LLC",
        paypoint_dba="Global Factory",
        external_paypoint_id="pay-10",
        org_name="SupplyPro",
        type="AUTHORIZATION",
        status="AUTHORIZATION",
        created_on="2026-05-05 03:28:53.082830",
        transaction_amount="74.500",
        posted_amount="0.000",
        merchant_name="Office Supply Co.",
        authorization_status="AUTHORIZATION",
    )
    """

    identifier: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="Identifier"),
        pydantic.Field(alias="Identifier", description="Unique identifier for the transaction."),
    ] = None
    card_token: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="CardToken"),
        pydantic.Field(alias="CardToken", description="Token of the virtual card associated with the transaction."),
    ] = None
    last_four: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="LastFour"),
        pydantic.Field(alias="LastFour", description="Last four digits of the masked virtual card number."),
    ] = None
    expiration_date: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="ExpirationDate"),
        pydantic.Field(
            alias="ExpirationDate", description="Expiration date of the virtual card used for the transaction."
        ),
    ] = None
    mcc: typing_extensions.Annotated[typing.Optional[Mcc], FieldMetadata(alias="Mcc"), pydantic.Field(alias="Mcc")] = (
        None
    )
    payout_id: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="PayoutId"),
        pydantic.Field(alias="PayoutId", description="Identifier of the payout linked to this transaction."),
    ] = None
    customer_id: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="CustomerId"),
        pydantic.Field(alias="CustomerId", description="Identifier of the customer linked to this transaction."),
    ] = None
    vendor_id: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="VendorId"),
        pydantic.Field(alias="VendorId", description="Identifier of the vendor linked to this transaction."),
    ] = None
    misc_data_1: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="MiscData1"),
        pydantic.Field(alias="MiscData1", description="Custom field 1 from the virtual card."),
    ] = None
    misc_data_2: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="MiscData2"),
        pydantic.Field(alias="MiscData2", description="Custom field 2 from the virtual card."),
    ] = None
    current_uses: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="CurrentUses"),
        pydantic.Field(alias="CurrentUses", description="Number of times the virtual card has been used."),
    ] = None
    amount: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="Amount"),
        pydantic.Field(alias="Amount", description="Authorized amount on the virtual card."),
    ] = None
    balance: typing_extensions.Annotated[
        typing.Optional[float],
        FieldMetadata(alias="Balance"),
        pydantic.Field(alias="Balance", description="Current balance remaining on the virtual card."),
    ] = None
    paypoint_id: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="PaypointId"),
        pydantic.Field(
            alias="PaypointId", description="Numeric identifier of the paypoint that issued the virtual card."
        ),
    ] = None
    paypoint_legal: typing_extensions.Annotated[
        typing.Optional[Legalname], FieldMetadata(alias="PaypointLegal"), pydantic.Field(alias="PaypointLegal")
    ] = None
    paypoint_dba: typing_extensions.Annotated[
        typing.Optional[Dbaname], FieldMetadata(alias="PaypointDba"), pydantic.Field(alias="PaypointDba")
    ] = None
    external_paypoint_id: typing_extensions.Annotated[
        typing.Optional[ExternalPaypointId],
        FieldMetadata(alias="ExternalPaypointID"),
        pydantic.Field(alias="ExternalPaypointID"),
    ] = None
    org_name: typing_extensions.Annotated[
        typing.Optional[OrgParentName], FieldMetadata(alias="OrgName"), pydantic.Field(alias="OrgName")
    ] = None
    type: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="Type"),
        pydantic.Field(alias="Type", description="Transaction type, such as `AUTHORIZATION`."),
    ] = None
    status: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="Status"),
        pydantic.Field(alias="Status", description="Transaction status, such as `AUTHORIZATION`."),
    ] = None
    created_on: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="CreatedOn"),
        pydantic.Field(
            alias="CreatedOn",
            description="Date and time the transaction was created. Format: `YYYY-MM-DD HH:MM:SS.ffffff`.",
        ),
    ] = None
    transaction_amount: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="TransactionAmount"),
        pydantic.Field(alias="TransactionAmount", description="Amount of the transaction, as a string value."),
    ] = None
    posted_amount: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="PostedAmount"),
        pydantic.Field(alias="PostedAmount", description="Posted amount of the transaction, as a string value."),
    ] = None
    posted_on: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="PostedOn"),
        pydantic.Field(
            alias="PostedOn",
            description="Date and time the transaction was posted, in format `YYYY-MM-DD HH:MM:SS.ffffff`. Null when the transaction hasn't posted yet.",
        ),
    ] = None
    merchant_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="MerchantName"),
        pydantic.Field(alias="MerchantName", description="Name of the merchant where the virtual card was used."),
    ] = None
    authorization_status: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="AuthorizationStatus"),
        pydantic.Field(alias="AuthorizationStatus", description="Authorization status of the transaction."),
    ] = None
    reason_to_decline: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="ReasonToDecline"),
        pydantic.Field(alias="ReasonToDecline", description="Reason the transaction was declined, when applicable."),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
