# This file was auto-generated by Fern from our API Definition.

import typing

GetProfileBillingRequestEntityType = typing.Union[
    typing.Literal["Organization", "Paypoint", "Template", "Application"], typing.Any
]
