# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.billing_profile_query_response import BillingProfileQueryResponse
from ..types.billing_profile_response import BillingProfileResponse
from .raw_client import AsyncRawBillingClient, RawBillingClient
from .types.get_profile_billing_request_entity_type import GetProfileBillingRequestEntityType
from .types.get_profile_billing_request_service_group import GetProfileBillingRequestServiceGroup


class BillingClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawBillingClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawBillingClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawBillingClient
        """
        return self._raw_client

    def list_profiles(
        self,
        org_id: int,
        *,
        profile_name: typing.Optional[str] = None,
        fee_type: typing.Optional[typing.Union[int, typing.Sequence[int]]] = None,
        service_vertical: typing.Optional[typing.Union[int, typing.Sequence[int]]] = None,
        profile_id: typing.Optional[int] = None,
        limit_record: typing.Optional[int] = None,
        from_record: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> BillingProfileQueryResponse:
        """
        Returns every billing profile that belongs to an organization. This is
        the data behind the Profile Library table in the Payabli Portal.

        Requires a token with the `billing_profile_read` permission; a token
        without it gets `403 Forbidden`.

        Parameters
        ----------
        org_id : int
            The organization's numeric identifier.

        profile_name : typing.Optional[str]
            Filter to profiles whose name contains this string.

        fee_type : typing.Optional[typing.Union[int, typing.Sequence[int]]]
            Filter by fee type. Repeatable to match more than one. Send the enum
            value (`1` Flat, `2` ICP).

        service_vertical : typing.Optional[typing.Union[int, typing.Sequence[int]]]
            Filter by billing vertical. Repeatable to match more than one. Send
            the enum value (`1` PayIn, `2` PayOut, `3` PayOps).

        profile_id : typing.Optional[int]
            Filter to a single profile by its identifier.

        limit_record : typing.Optional[int]
            Page size. Defaults to `20`. Passing `0` returns no records — use a
            positive value to page through results.

        from_record : typing.Optional[int]
            Zero-based offset into the result set. Defaults to `0`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BillingProfileQueryResponse
            A page of billing profiles.

        Examples
        --------
        from payabli import payabli

        client = payabli(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.billing.list_profiles(
            org_id=123,
            limit_record=20,
            from_record=0,
        )
        """
        _response = self._raw_client.list_profiles(
            org_id,
            profile_name=profile_name,
            fee_type=fee_type,
            service_vertical=service_vertical,
            profile_id=profile_id,
            limit_record=limit_record,
            from_record=from_record,
            request_options=request_options,
        )
        return _response.data

    def get_profile(
        self,
        service_group: GetProfileBillingRequestServiceGroup,
        entity_type: GetProfileBillingRequestEntityType,
        entity_id: int,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> BillingProfileResponse:
        """
        Returns the billing profile currently assigned to an entity, including
        its billable events and fee schedules. Use it to read the pricing terms
        in effect for an organization, paypoint, template, or application.

        Requires a token with the `billing_profile_read` permission and access
        to the requested entity; otherwise the call gets `403 Forbidden`.

        If the entity exists but has no profile assigned, the call returns
        `404 Not Found`.

        Parameters
        ----------
        service_group : GetProfileBillingRequestServiceGroup
            The billing vertical. Only `PayIn` and `PayOut` are accepted; any
            other value returns `400 Bad Request`.

        entity_type : GetProfileBillingRequestEntityType
            The owning entity type: `Organization`, `Paypoint`, `Template`, or
            `Application`.

        entity_id : int
            The numeric identifier of the entity.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BillingProfileResponse
            The billing profile assigned to the entity.

        Examples
        --------
        from payabli import payabli

        client = payabli(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )
        client.billing.get_profile(
            service_group="PayIn",
            entity_type="Organization",
            entity_id=123,
        )
        """
        _response = self._raw_client.get_profile(service_group, entity_type, entity_id, request_options=request_options)
        return _response.data


class AsyncBillingClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawBillingClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawBillingClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawBillingClient
        """
        return self._raw_client

    async def list_profiles(
        self,
        org_id: int,
        *,
        profile_name: typing.Optional[str] = None,
        fee_type: typing.Optional[typing.Union[int, typing.Sequence[int]]] = None,
        service_vertical: typing.Optional[typing.Union[int, typing.Sequence[int]]] = None,
        profile_id: typing.Optional[int] = None,
        limit_record: typing.Optional[int] = None,
        from_record: typing.Optional[int] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> BillingProfileQueryResponse:
        """
        Returns every billing profile that belongs to an organization. This is
        the data behind the Profile Library table in the Payabli Portal.

        Requires a token with the `billing_profile_read` permission; a token
        without it gets `403 Forbidden`.

        Parameters
        ----------
        org_id : int
            The organization's numeric identifier.

        profile_name : typing.Optional[str]
            Filter to profiles whose name contains this string.

        fee_type : typing.Optional[typing.Union[int, typing.Sequence[int]]]
            Filter by fee type. Repeatable to match more than one. Send the enum
            value (`1` Flat, `2` ICP).

        service_vertical : typing.Optional[typing.Union[int, typing.Sequence[int]]]
            Filter by billing vertical. Repeatable to match more than one. Send
            the enum value (`1` PayIn, `2` PayOut, `3` PayOps).

        profile_id : typing.Optional[int]
            Filter to a single profile by its identifier.

        limit_record : typing.Optional[int]
            Page size. Defaults to `20`. Passing `0` returns no records — use a
            positive value to page through results.

        from_record : typing.Optional[int]
            Zero-based offset into the result set. Defaults to `0`.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BillingProfileQueryResponse
            A page of billing profiles.

        Examples
        --------
        import asyncio

        from payabli import Asyncpayabli

        client = Asyncpayabli(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.billing.list_profiles(
                org_id=123,
                limit_record=20,
                from_record=0,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.list_profiles(
            org_id,
            profile_name=profile_name,
            fee_type=fee_type,
            service_vertical=service_vertical,
            profile_id=profile_id,
            limit_record=limit_record,
            from_record=from_record,
            request_options=request_options,
        )
        return _response.data

    async def get_profile(
        self,
        service_group: GetProfileBillingRequestServiceGroup,
        entity_type: GetProfileBillingRequestEntityType,
        entity_id: int,
        *,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> BillingProfileResponse:
        """
        Returns the billing profile currently assigned to an entity, including
        its billable events and fee schedules. Use it to read the pricing terms
        in effect for an organization, paypoint, template, or application.

        Requires a token with the `billing_profile_read` permission and access
        to the requested entity; otherwise the call gets `403 Forbidden`.

        If the entity exists but has no profile assigned, the call returns
        `404 Not Found`.

        Parameters
        ----------
        service_group : GetProfileBillingRequestServiceGroup
            The billing vertical. Only `PayIn` and `PayOut` are accepted; any
            other value returns `400 Bad Request`.

        entity_type : GetProfileBillingRequestEntityType
            The owning entity type: `Organization`, `Paypoint`, `Template`, or
            `Application`.

        entity_id : int
            The numeric identifier of the entity.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        BillingProfileResponse
            The billing profile assigned to the entity.

        Examples
        --------
        import asyncio

        from payabli import Asyncpayabli

        client = Asyncpayabli(
            client_id="YOUR_CLIENT_ID",
            client_secret="YOUR_CLIENT_SECRET",
        )


        async def main() -> None:
            await client.billing.get_profile(
                service_group="PayIn",
                entity_type="Organization",
                entity_id=123,
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.get_profile(
            service_group, entity_type, entity_id, request_options=request_options
        )
        return _response.data
