# This file was auto-generated by Fern from our API Definition.

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from .raw_client import AsyncRawManagementClient, RawManagementClient
from .types.verify_account_details_response import VerifyAccountDetailsResponse

# this is used as the default value for optional parameters
OMIT = typing.cast(typing.Any, ...)


class ManagementClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawManagementClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawManagementClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawManagementClient
        """
        return self._raw_client

    def verify_account_details(
        self,
        entry: str,
        *,
        routing_number: str,
        account_number: str,
        account_type: typing.Optional[str] = OMIT,
        country: typing.Optional[str] = OMIT,
        account_holder_type: typing.Optional[str] = OMIT,
        holder_name: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> VerifyAccountDetailsResponse:
        """
        Verifies a bank account and returns detailed verification results from the verification network, including bank name, account status, and response codes. Unlike a pass/fail verification, this endpoint returns granular data to support decision-making and troubleshooting.

        When bank authentication is enabled for the paypoint's organization, the endpoint performs an identity verification check on the account holder. Otherwise, it performs an account existence check. When bank authentication is enabled, the `accountHolderType` and `holderName` fields are required.

        Requires `inboundpayments_create` or `outboundpayments_create` permission.

        Parameters
        ----------
        entry : str
            The paypoint's entry name identifier.

        routing_number : str
            The bank routing number to verify.

        account_number : str
            The bank account number to verify.

        account_type : typing.Optional[str]
            The type of bank account, such as `Checking` or `Savings`.

        country : typing.Optional[str]
            The ISO country code for the bank account, such as `US`.

        account_holder_type : typing.Optional[str]
            The type of account holder. Accepted values are `personal` or `business`. Required when bank authentication is enabled for the paypoint's organization.

        holder_name : typing.Optional[str]
            The name of the bank account holder. For personal accounts, provide the holder's full name (for example, `Jane Doe`); the value is split on the first space into first and last name. For business accounts, provide the legal business name. Required when bank authentication is enabled for the paypoint's organization.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        VerifyAccountDetailsResponse
            Success

        Examples
        --------
        from payabli import payabli

        client = payabli(
            api_key="YOUR_API_KEY",
        )
        client.management.verify_account_details(
            entry="entry752",
            routing_number="122105278",
            account_number="0000000016",
            account_type="Checking",
            country="US",
            account_holder_type="personal",
            holder_name="Jane Doe",
        )
        """
        _response = self._raw_client.verify_account_details(
            entry,
            routing_number=routing_number,
            account_number=account_number,
            account_type=account_type,
            country=country,
            account_holder_type=account_holder_type,
            holder_name=holder_name,
            request_options=request_options,
        )
        return _response.data


class AsyncManagementClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawManagementClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawManagementClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawManagementClient
        """
        return self._raw_client

    async def verify_account_details(
        self,
        entry: str,
        *,
        routing_number: str,
        account_number: str,
        account_type: typing.Optional[str] = OMIT,
        country: typing.Optional[str] = OMIT,
        account_holder_type: typing.Optional[str] = OMIT,
        holder_name: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> VerifyAccountDetailsResponse:
        """
        Verifies a bank account and returns detailed verification results from the verification network, including bank name, account status, and response codes. Unlike a pass/fail verification, this endpoint returns granular data to support decision-making and troubleshooting.

        When bank authentication is enabled for the paypoint's organization, the endpoint performs an identity verification check on the account holder. Otherwise, it performs an account existence check. When bank authentication is enabled, the `accountHolderType` and `holderName` fields are required.

        Requires `inboundpayments_create` or `outboundpayments_create` permission.

        Parameters
        ----------
        entry : str
            The paypoint's entry name identifier.

        routing_number : str
            The bank routing number to verify.

        account_number : str
            The bank account number to verify.

        account_type : typing.Optional[str]
            The type of bank account, such as `Checking` or `Savings`.

        country : typing.Optional[str]
            The ISO country code for the bank account, such as `US`.

        account_holder_type : typing.Optional[str]
            The type of account holder. Accepted values are `personal` or `business`. Required when bank authentication is enabled for the paypoint's organization.

        holder_name : typing.Optional[str]
            The name of the bank account holder. For personal accounts, provide the holder's full name (for example, `Jane Doe`); the value is split on the first space into first and last name. For business accounts, provide the legal business name. Required when bank authentication is enabled for the paypoint's organization.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        VerifyAccountDetailsResponse
            Success

        Examples
        --------
        import asyncio

        from payabli import Asyncpayabli

        client = Asyncpayabli(
            api_key="YOUR_API_KEY",
        )


        async def main() -> None:
            await client.management.verify_account_details(
                entry="entry752",
                routing_number="122105278",
                account_number="0000000016",
                account_type="Checking",
                country="US",
                account_holder_type="personal",
                holder_name="Jane Doe",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.verify_account_details(
            entry,
            routing_number=routing_number,
            account_number=account_number,
            account_type=account_type,
            country=country,
            account_holder_type=account_holder_type,
            holder_name=holder_name,
            request_options=request_options,
        )
        return _response.data
