# This file was auto-generated by Fern from our API Definition.

import typing

import pydantic
import typing_extensions
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ...core.serialization import FieldMetadata


class CreateApplicationFromPaypointRequest(UniversalBaseModel):
    """
    Request to create a boarding application linked to an existing paypoint. Used for adding new services to a paypoint without creating a duplicate record.
    """

    paypoint_id: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="paypointId"),
        pydantic.Field(alias="paypointId", description="ID of the existing paypoint to link to this application."),
    ]
    template_id: typing_extensions.Annotated[
        int,
        FieldMetadata(alias="templateId"),
        pydantic.Field(alias="templateId", description="ID of the boarding template to use for the new application."),
    ]
    recipient_email: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="recipientEmail"),
        pydantic.Field(
            alias="recipientEmail",
            description="Email address where the boarding link is sent. Required. If you don't want to email the merchant, send to an internal address and use `returnBoardingAccessInfoInLine` to retrieve the link from the response instead.",
        ),
    ]
    return_boarding_access_info_in_line: typing_extensions.Annotated[
        typing.Optional[bool],
        FieldMetadata(alias="returnBoardingAccessInfoInLine"),
        pydantic.Field(
            alias="returnBoardingAccessInfoInLine",
            description="When `true`, returns the boarding access information directly in the response.",
        ),
    ] = None
    on_create: typing_extensions.Annotated[
        typing.Optional[typing.List[str]],
        FieldMetadata(alias="onCreate"),
        pydantic.Field(
            alias="onCreate",
            description="Additional actions to trigger when the application is created. Currently only `submitApplication` is supported, which automatically submits the application on creation and skips the draft state.",
        ),
    ] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
